# Generated by Django 5.0.9 on 2025-10-30 16:51

import djmoney.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_user_is_tenant_owner_user_tenant"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="collection_zone",
            field=models.CharField(
                blank=True,
                help_text="Zona de cobranza asignada (ej: Zona Norte, Zona Este, etc.)",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="daily_collection_target",
            field=djmoney.models.fields.MoneyField(
                blank=True,
                decimal_places=2,
                help_text="Meta diaria de cobros para el cobrador",
                max_digits=12,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="daily_collection_target_currency",
            field=djmoney.models.fields.CurrencyField(
                choices=[
                    ("DOP", "Dominican Peso"),
                    ("EUR", "Euro"),
                    ("USD", "US Dollar"),
                ],
                default="USD",
                editable=False,
                max_length=3,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Administrator"),
                    ("manager", "Manager"),
                    ("loan_officer", "Loan Officer"),
                    ("collector", "Cobrador"),
                    ("collection_supervisor", "Supervisor de Cobranza"),
                    ("accountant", "Accountant"),
                    ("cashier", "Cashier"),
                    ("viewer", "Viewer"),
                ],
                default="viewer",
                max_length=30,
            ),
        ),
    ]
