# Generated by Django 5.0.9 on 2025-12-14 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_add_collection_roles"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="backup_codes",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of backup codes for 2FA recovery",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="is_2fa_enabled",
            field=models.BooleanField(
                default=False,
                help_text="Whether two-factor authentication is enabled for this user",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="totp_secret",
            field=models.CharField(
                blank=True,
                help_text="TOTP secret key for 2FA (Google Authenticator compatible)",
                max_length=32,
                null=True,
            ),
        ),
    ]
