# Generated by Django 5.0.9 on 2026-03-29 22:01

import djmoney.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_add_2fa_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="daily_collection_target",
            field=djmoney.models.fields.MoneyField(
                blank=True,
                decimal_places=2,
                default_currency="USD",
                help_text="Meta diaria de cobros para el cobrador",
                max_digits=12,
                null=True,
            ),
        ),
    ]
