# Generated by Django 5.0.9 on 2026-04-03 20:42

import djmoney.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_alter_user_daily_collection_target"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="daily_collection_target",
            field=djmoney.models.fields.MoneyField(
                blank=True,
                decimal_places=2,
                help_text="Meta diaria de cobros para el cobrador",
                max_digits=12,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="daily_collection_target_currency",
            field=djmoney.models.fields.CurrencyField(
                choices=[
                    ("DOP", "Dominican Peso"),
                    ("EUR", "Euro"),
                    ("USD", "US Dollar"),
                ],
                default="DOP",
                editable=False,
                max_length=3,
                null=True,
            ),
        ),
    ]
