# Generated by Django 5.0.9 on 2025-12-14 00:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tenants", "0006_tenant_imap_host_tenant_imap_password_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "user_email",
                    models.EmailField(
                        help_text="Email of user at time of action (preserved even if user is deleted)",
                        max_length=254,
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("create", "Crear"),
                            ("update", "Actualizar"),
                            ("delete", "Eliminar"),
                            ("approve", "Aprobar"),
                            ("reject", "Rechazar"),
                            ("disburse", "Desembolsar"),
                            ("close", "Cerrar"),
                            ("payment", "Pago"),
                            ("payment_void", "Anular Pago"),
                            ("login", "Iniciar Sesion"),
                            ("logout", "Cerrar Sesion"),
                            ("login_failed", "Login Fallido"),
                            ("password_change", "Cambio de Contrasena"),
                            ("password_reset", "Reseteo de Contrasena"),
                            ("2fa_enable", "Habilitar 2FA"),
                            ("2fa_disable", "Deshabilitar 2FA"),
                            ("permission_change", "Cambio de Permisos"),
                            ("role_change", "Cambio de Rol"),
                            ("export", "Exportar"),
                            ("import", "Importar"),
                            ("config_change", "Cambio de Configuracion"),
                        ],
                        db_index=True,
                        help_text="Type of action performed",
                        max_length=50,
                    ),
                ),
                (
                    "model_name",
                    models.CharField(
                        db_index=True,
                        help_text="Name of the model affected",
                        max_length=100,
                    ),
                ),
                (
                    "object_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Primary key of the object affected",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "object_repr",
                    models.CharField(
                        help_text="String representation of the object", max_length=255
                    ),
                ),
                (
                    "changes",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Dictionary of field changes: {field: {old: value, new: value}}",
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, help_text="IP address of the request", null=True
                    ),
                ),
                (
                    "user_agent",
                    models.TextField(
                        blank=True, help_text="User agent of the request", null=True
                    ),
                ),
                (
                    "extra_data",
                    models.JSONField(
                        blank=True, default=dict, help_text="Additional context data"
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="When the action occurred",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        help_text="Tenant to which this log belongs",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audit_logs",
                        to="tenants.tenant",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who performed the action",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Registro de Auditoria",
                "verbose_name_plural": "Registros de Auditoria",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["tenant", "-timestamp"],
                        name="audit_audit_tenant__1b7744_idx",
                    ),
                    models.Index(
                        fields=["tenant", "action"],
                        name="audit_audit_tenant__b14d1a_idx",
                    ),
                    models.Index(
                        fields=["tenant", "model_name"],
                        name="audit_audit_tenant__0d0d71_idx",
                    ),
                    models.Index(
                        fields=["tenant", "user"], name="audit_audit_tenant__dcc56d_idx"
                    ),
                ],
            },
        ),
    ]
