# Generated by Django 5.0.9 on 2026-03-29 22:01

import django.core.validators
import django.db.models.deletion
import djmoney.models.fields
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("loans", "0015_alter_collateral_appraisal_value_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DigitalCertificate",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Nombre descriptivo del certificado", max_length=255
                    ),
                ),
                (
                    "certificate_file",
                    models.FileField(
                        help_text="Archivo del certificado digital (.p12 / .pfx)",
                        upload_to="billing/certificates/",
                    ),
                ),
                (
                    "certificate_password",
                    models.CharField(
                        help_text="Contraseña del certificado (almacenada encriptada)",
                        max_length=255,
                    ),
                ),
                (
                    "issuer",
                    models.CharField(
                        blank=True,
                        help_text="Entidad emisora del certificado",
                        max_length=255,
                    ),
                ),
                (
                    "serial_number",
                    models.CharField(
                        blank=True,
                        help_text="Número de serie del certificado",
                        max_length=255,
                    ),
                ),
                (
                    "valid_from",
                    models.DateTimeField(
                        blank=True, help_text="Fecha de inicio de validez", null=True
                    ),
                ),
                (
                    "valid_until",
                    models.DateTimeField(
                        blank=True,
                        help_text="Fecha de expiración del certificado",
                        null=True,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Certificado activo para firmar e-CF"
                    ),
                ),
            ],
            options={
                "verbose_name": "Certificado Digital",
                "verbose_name_plural": "Certificados Digitales",
                "ordering": ["-is_active", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="FiscalSequence",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "ecf_type",
                    models.CharField(
                        choices=[
                            ("31", "Factura de Crédito Fiscal Electrónica"),
                            ("32", "Factura de Consumo Electrónica"),
                            ("33", "Nota de Débito Electrónica"),
                            ("34", "Nota de Crédito Electrónica"),
                            ("41", "Compras Electrónico"),
                            ("43", "Gastos Menores Electrónico"),
                            ("44", "Regímenes Especiales Electrónico"),
                            ("45", "Gubernamental Electrónico"),
                            ("46", "Comprobante de Exportaciones Electrónico"),
                            ("47", "Comprobante para Pagos al Exterior Electrónico"),
                        ],
                        help_text="Tipo de comprobante fiscal electrónico",
                        max_length=2,
                    ),
                ),
                (
                    "prefix",
                    models.CharField(
                        help_text="Prefijo de la secuencia (ej: E31, E32)", max_length=3
                    ),
                ),
                (
                    "range_from",
                    models.BigIntegerField(help_text="Inicio del rango autorizado"),
                ),
                (
                    "range_to",
                    models.BigIntegerField(help_text="Fin del rango autorizado"),
                ),
                (
                    "current_number",
                    models.BigIntegerField(help_text="Próximo número a utilizar"),
                ),
                (
                    "expiration_date",
                    models.DateField(
                        blank=True,
                        help_text="Fecha de vencimiento de la secuencia",
                        null=True,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Secuencia activa para emisión"
                    ),
                ),
                (
                    "authorization_number",
                    models.CharField(
                        blank=True,
                        help_text="Número de autorización DGII",
                        max_length=50,
                    ),
                ),
            ],
            options={
                "verbose_name": "Secuencia Fiscal",
                "verbose_name_plural": "Secuencias Fiscales",
                "ordering": ["ecf_type", "-is_active"],
                "unique_together": {("ecf_type", "prefix", "range_from")},
            },
        ),
        migrations.CreateModel(
            name="Invoice",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "ecf_type",
                    models.CharField(
                        choices=[
                            ("31", "Factura de Crédito Fiscal Electrónica"),
                            ("32", "Factura de Consumo Electrónica"),
                            ("33", "Nota de Débito Electrónica"),
                            ("34", "Nota de Crédito Electrónica"),
                            ("41", "Compras Electrónico"),
                            ("43", "Gastos Menores Electrónico"),
                            ("44", "Regímenes Especiales Electrónico"),
                            ("45", "Gubernamental Electrónico"),
                            ("46", "Comprobante de Exportaciones Electrónico"),
                            ("47", "Comprobante para Pagos al Exterior Electrónico"),
                        ],
                        default="31",
                        help_text="Tipo de comprobante fiscal electrónico",
                        max_length=2,
                    ),
                ),
                (
                    "encf_number",
                    models.CharField(
                        blank=True,
                        help_text="Número de Comprobante Fiscal Electrónico (e-NCF)",
                        max_length=13,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "security_code",
                    models.CharField(
                        blank=True,
                        help_text="Código de seguridad para QR",
                        max_length=6,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Borrador"),
                            ("generated", "XML Generado"),
                            ("signed", "Firmado"),
                            ("submitted", "Enviado a DGII"),
                            ("accepted", "Aceptado por DGII"),
                            ("conditionally_accepted", "Aceptado Condicional"),
                            ("rejected", "Rechazado por DGII"),
                            ("cancelled", "Anulado"),
                        ],
                        default="draft",
                        help_text="Estado actual de la factura",
                        max_length=30,
                    ),
                ),
                (
                    "emisor_rnc",
                    models.CharField(
                        blank=True, help_text="RNC/Cédula del emisor", max_length=11
                    ),
                ),
                (
                    "emisor_razon_social",
                    models.CharField(
                        blank=True, help_text="Razón social del emisor", max_length=255
                    ),
                ),
                (
                    "comprador_rnc",
                    models.CharField(
                        blank=True, help_text="RNC/Cédula del comprador", max_length=11
                    ),
                ),
                (
                    "comprador_razon_social",
                    models.CharField(
                        blank=True,
                        help_text="Nombre/Razón social del comprador",
                        max_length=255,
                    ),
                ),
                ("issue_date", models.DateField(help_text="Fecha de emisión")),
                (
                    "due_date",
                    models.DateField(
                        blank=True, help_text="Fecha de vencimiento del pago", null=True
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("01", "Efectivo"),
                            ("02", "Cheque / Transferencia / Depósito"),
                            ("03", "Tarjeta de Crédito / Débito"),
                            ("04", "Venta a Crédito"),
                            ("05", "Permuta"),
                            ("06", "Nota de Crédito"),
                            ("07", "Mixto"),
                        ],
                        default="04",
                        help_text="Forma de pago",
                        max_length=2,
                    ),
                ),
                (
                    "subtotal_currency",
                    djmoney.models.fields.CurrencyField(
                        choices=[
                            ("DOP", "Dominican Peso"),
                            ("EUR", "Euro"),
                            ("USD", "US Dollar"),
                        ],
                        default="DOP",
                        editable=False,
                        max_length=3,
                    ),
                ),
                (
                    "subtotal",
                    djmoney.models.fields.MoneyField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Subtotal antes de impuestos",
                        max_digits=14,
                    ),
                ),
                (
                    "total_itbis_currency",
                    djmoney.models.fields.CurrencyField(
                        choices=[
                            ("DOP", "Dominican Peso"),
                            ("EUR", "Euro"),
                            ("USD", "US Dollar"),
                        ],
                        default="DOP",
                        editable=False,
                        max_length=3,
                    ),
                ),
                (
                    "total_itbis",
                    djmoney.models.fields.MoneyField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Total ITBIS (impuesto)",
                        max_digits=14,
                    ),
                ),
                (
                    "total_discount_currency",
                    djmoney.models.fields.CurrencyField(
                        choices=[
                            ("DOP", "Dominican Peso"),
                            ("EUR", "Euro"),
                            ("USD", "US Dollar"),
                        ],
                        default="DOP",
                        editable=False,
                        max_length=3,
                    ),
                ),
                (
                    "total_discount",
                    djmoney.models.fields.MoneyField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Total descuentos",
                        max_digits=14,
                    ),
                ),
                (
                    "total_currency",
                    djmoney.models.fields.CurrencyField(
                        choices=[
                            ("DOP", "Dominican Peso"),
                            ("EUR", "Euro"),
                            ("USD", "US Dollar"),
                        ],
                        default="DOP",
                        editable=False,
                        max_length=3,
                    ),
                ),
                (
                    "total",
                    djmoney.models.fields.MoneyField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Monto total de la factura",
                        max_digits=14,
                    ),
                ),
                (
                    "xml_content",
                    models.TextField(
                        blank=True, help_text="XML del e-CF generado (sin firmar)"
                    ),
                ),
                (
                    "signed_xml",
                    models.TextField(
                        blank=True, help_text="XML del e-CF firmado digitalmente"
                    ),
                ),
                (
                    "dgii_trackid",
                    models.CharField(
                        blank=True,
                        help_text="TrackId recibido de la DGII",
                        max_length=100,
                    ),
                ),
                (
                    "dgii_status",
                    models.CharField(
                        blank=True, help_text="Estado en la DGII", max_length=50
                    ),
                ),
                (
                    "dgii_response",
                    models.JSONField(
                        blank=True,
                        help_text="Respuesta completa de la DGII (JSON)",
                        null=True,
                    ),
                ),
                (
                    "dgii_submitted_at",
                    models.DateTimeField(
                        blank=True, help_text="Fecha/hora de envío a DGII", null=True
                    ),
                ),
                ("notes", models.TextField(blank=True, help_text="Notas internas")),
                (
                    "certificate",
                    models.ForeignKey(
                        blank=True,
                        help_text="Certificado utilizado para firmar",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="invoices",
                        to="billing.digitalcertificate",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        help_text="Cliente/comprador",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="invoices",
                        to="loans.customer",
                    ),
                ),
                (
                    "fiscal_sequence",
                    models.ForeignKey(
                        blank=True,
                        help_text="Secuencia fiscal utilizada",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="invoices",
                        to="billing.fiscalsequence",
                    ),
                ),
                (
                    "loan",
                    models.ForeignKey(
                        blank=True,
                        help_text="Préstamo asociado",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="invoices",
                        to="loans.loan",
                    ),
                ),
                (
                    "payment",
                    models.ForeignKey(
                        blank=True,
                        help_text="Pago de préstamo asociado",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="invoices",
                        to="loans.loanpayment",
                    ),
                ),
                (
                    "reference_invoice",
                    models.ForeignKey(
                        blank=True,
                        help_text="Factura original (para NC/ND)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="credit_debit_notes",
                        to="billing.invoice",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Factura Electrónica",
                "verbose_name_plural": "Facturas Electrónicas",
                "ordering": ["-issue_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ECFSubmission",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("submit", "Envío de e-CF"),
                            ("query_status", "Consulta de Estado"),
                            ("query_result", "Consulta de Resultado"),
                            ("cancel", "Anulación"),
                        ],
                        help_text="Tipo de acción realizada",
                        max_length=30,
                    ),
                ),
                (
                    "environment",
                    models.CharField(
                        choices=[
                            ("testecf", "Pre-Certificación (Pruebas)"),
                            ("certecf", "Certificación"),
                            ("ecf", "Producción"),
                        ],
                        help_text="Ambiente DGII utilizado",
                        max_length=10,
                    ),
                ),
                (
                    "trackid",
                    models.CharField(
                        blank=True, help_text="TrackId de la DGII", max_length=100
                    ),
                ),
                (
                    "request_xml",
                    models.TextField(blank=True, help_text="XML enviado a la DGII"),
                ),
                (
                    "response_status",
                    models.CharField(
                        blank=True, help_text="Estado de la respuesta", max_length=50
                    ),
                ),
                (
                    "response_body",
                    models.JSONField(
                        blank=True,
                        help_text="Cuerpo completo de la respuesta",
                        null=True,
                    ),
                ),
                (
                    "http_status_code",
                    models.IntegerField(
                        blank=True, help_text="Código HTTP de la respuesta", null=True
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True, help_text="Mensaje de error (si aplica)"
                    ),
                ),
                (
                    "submitted_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Fecha/hora del envío"
                    ),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        help_text="Factura enviada",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submissions",
                        to="billing.invoice",
                    ),
                ),
            ],
            options={
                "verbose_name": "Envío a DGII",
                "verbose_name_plural": "Envíos a DGII",
                "ordering": ["-submitted_at"],
            },
        ),
        migrations.CreateModel(
            name="InvoiceItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "line_number",
                    models.PositiveIntegerField(help_text="Número de línea"),
                ),
                (
                    "description",
                    models.CharField(
                        help_text="Descripción del bien o servicio", max_length=500
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("1.0000"),
                        help_text="Cantidad",
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.0001"))
                        ],
                    ),
                ),
                (
                    "unit_price_currency",
                    djmoney.models.fields.CurrencyField(
                        choices=[
                            ("DOP", "Dominican Peso"),
                            ("EUR", "Euro"),
                            ("USD", "US Dollar"),
                        ],
                        default="DOP",
                        editable=False,
                        max_length=3,
                    ),
                ),
                (
                    "unit_price",
                    djmoney.models.fields.MoneyField(
                        decimal_places=2, help_text="Precio unitario", max_digits=14
                    ),
                ),
                (
                    "discount_amount_currency",
                    djmoney.models.fields.CurrencyField(
                        choices=[
                            ("DOP", "Dominican Peso"),
                            ("EUR", "Euro"),
                            ("USD", "US Dollar"),
                        ],
                        default="DOP",
                        editable=False,
                        max_length=3,
                    ),
                ),
                (
                    "discount_amount",
                    djmoney.models.fields.MoneyField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Monto de descuento",
                        max_digits=14,
                    ),
                ),
                (
                    "itbis_rate",
                    models.CharField(
                        choices=[
                            ("18", "18% (Tasa General)"),
                            ("16", "16% (Tasa Reducida)"),
                            ("0", "0% (Exento)"),
                        ],
                        default="18",
                        help_text="Tasa de ITBIS aplicable",
                        max_length=2,
                    ),
                ),
                (
                    "itbis_amount_currency",
                    djmoney.models.fields.CurrencyField(
                        choices=[
                            ("DOP", "Dominican Peso"),
                            ("EUR", "Euro"),
                            ("USD", "US Dollar"),
                        ],
                        default="DOP",
                        editable=False,
                        max_length=3,
                    ),
                ),
                (
                    "itbis_amount",
                    djmoney.models.fields.MoneyField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Monto de ITBIS calculado",
                        max_digits=14,
                    ),
                ),
                (
                    "total_currency",
                    djmoney.models.fields.CurrencyField(
                        choices=[
                            ("DOP", "Dominican Peso"),
                            ("EUR", "Euro"),
                            ("USD", "US Dollar"),
                        ],
                        default="DOP",
                        editable=False,
                        max_length=3,
                    ),
                ),
                (
                    "total",
                    djmoney.models.fields.MoneyField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Total de la línea (cantidad × precio - descuento + ITBIS)",
                        max_digits=14,
                    ),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        help_text="Factura a la que pertenece",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="billing.invoice",
                    ),
                ),
            ],
            options={
                "verbose_name": "Línea de Factura",
                "verbose_name_plural": "Líneas de Factura",
                "ordering": ["invoice", "line_number"],
            },
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(
                fields=["encf_number"], name="billing_inv_encf_nu_70df8a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(fields=["status"], name="billing_inv_status_541249_idx"),
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(
                fields=["ecf_type"], name="billing_inv_ecf_typ_c8e5da_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(
                fields=["issue_date"], name="billing_inv_issue_d_0996ee_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(
                fields=["dgii_trackid"], name="billing_inv_dgii_tr_fe0e14_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="invoiceitem",
            unique_together={("invoice", "line_number")},
        ),
    ]
