# Generated by Django 5.0.9 on 2025-10-28 16:31

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import djmoney.models.fields
import phonenumber_field.modelfields
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "customer_id",
                    models.CharField(editable=False, max_length=50, unique=True),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                (
                    "middle_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("date_of_birth", models.DateField()),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[("M", "Male"), ("F", "Female"), ("O", "Other")],
                        max_length=10,
                        null=True,
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                (
                    "phone",
                    phonenumber_field.modelfields.PhoneNumberField(
                        max_length=128, region=None
                    ),
                ),
                (
                    "alternate_phone",
                    phonenumber_field.modelfields.PhoneNumberField(
                        blank=True, max_length=128, null=True, region=None
                    ),
                ),
                ("address_line1", models.CharField(max_length=255)),
                (
                    "address_line2",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("city", models.CharField(max_length=100)),
                ("state", models.CharField(max_length=100)),
                (
                    "country",
                    models.CharField(default="Dominican Republic", max_length=100),
                ),
                ("postal_code", models.CharField(max_length=20)),
                (
                    "id_type",
                    models.CharField(
                        choices=[
                            ("cedula", "Cédula"),
                            ("passport", "Passport"),
                            ("driver_license", "Driver License"),
                        ],
                        max_length=50,
                    ),
                ),
                ("id_number", models.CharField(max_length=50, unique=True)),
                ("id_expiry_date", models.DateField(blank=True, null=True)),
                (
                    "id_document",
                    models.FileField(
                        blank=True, null=True, upload_to="customer_documents/ids/"
                    ),
                ),
                (
                    "employment_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("employed", "Employed"),
                            ("self_employed", "Self Employed"),
                            ("unemployed", "Unemployed"),
                            ("retired", "Retired"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "employer_name",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("occupation", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "monthly_income_currency",
                    djmoney.models.fields.CurrencyField(
                        choices=[
                            ("DOP", "Dominican Peso"),
                            ("EUR", "Euro"),
                            ("USD", "US Dollar"),
                        ],
                        default="USD",
                        editable=False,
                        max_length=3,
                        null=True,
                    ),
                ),
                (
                    "monthly_income",
                    djmoney.models.fields.MoneyField(
                        blank=True, decimal_places=2, max_digits=14, null=True
                    ),
                ),
                (
                    "credit_score",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(300),
                            django.core.validators.MaxValueValidator(850),
                        ],
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("blacklisted", "Blacklisted"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "photo",
                    models.ImageField(
                        blank=True, null=True, upload_to="customer_photos/"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "customers",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Loan",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "loan_number",
                    models.CharField(editable=False, max_length=50, unique=True),
                ),
                (
                    "loan_type",
                    models.CharField(
                        choices=[
                            ("personal", "Personal Loan"),
                            ("auto", "Auto Loan"),
                            ("mortgage", "Mortgage"),
                            ("business", "Business Loan"),
                            ("student", "Student Loan"),
                            ("payday", "Payday Loan"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "principal_amount_currency",
                    djmoney.models.fields.CurrencyField(
                        choices=[
                            ("DOP", "Dominican Peso"),
                            ("EUR", "Euro"),
                            ("USD", "US Dollar"),
                        ],
                        default="USD",
                        editable=False,
                        max_length=3,
                    ),
                ),
                (
                    "principal_amount",
                    djmoney.models.fields.MoneyField(
                        decimal_places=2,
                        max_digits=14,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                (
                    "interest_rate",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Annual interest rate in percentage",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "term_months",
                    models.IntegerField(
                        help_text="Loan term in months",
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "payment_frequency",
                    models.CharField(
                        choices=[
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                            ("biweekly", "Bi-Weekly"),
                            ("monthly", "Monthly"),
                            ("quarterly", "Quarterly"),
                        ],
                        default="monthly",
                        max_length=20,
                    ),
                ),
                (
                    "payment_amount_currency",
                    djmoney.models.fields.CurrencyField(
                        choices=[
                            ("DOP", "Dominican Peso"),
                            ("EUR", "Euro"),
                            ("USD", "US Dollar"),
                        ],
                        default="USD",
                        editable=False,
                        max_length=3,
                    ),
                ),
                (
                    "payment_amount",
                    djmoney.models.fields.MoneyField(
                        decimal_places=2,
                        help_text="Regular payment amount",
                        max_digits=14,
                    ),
                ),
                (
                    "application_date",
                    models.DateField(default=django.utils.timezone.now),
                ),
                ("approval_date", models.DateField(blank=True, null=True)),
                ("disbursement_date", models.DateField(blank=True, null=True)),
                ("first_payment_date", models.DateField(blank=True, null=True)),
                ("maturity_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("pending", "Pending Approval"),
                            ("approved", "Approved"),
                            ("active", "Active"),
                            ("paid", "Paid Off"),
                            ("defaulted", "Defaulted"),
                            ("written_off", "Written Off"),
                            ("rejected", "Rejected"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "outstanding_balance_currency",
                    djmoney.models.fields.CurrencyField(
                        choices=[
                            ("DOP", "Dominican Peso"),
                            ("EUR", "Euro"),
                            ("USD", "US Dollar"),
                        ],
                        default="USD",
                        editable=False,
                        max_length=3,
                    ),
                ),
                (
                    "outstanding_balance",
                    djmoney.models.fields.MoneyField(
                        decimal_places=2, default=Decimal("0"), max_digits=14
                    ),
                ),
                (
                    "total_paid_currency",
                    djmoney.models.fields.CurrencyField(
                        choices=[
                            ("DOP", "Dominican Peso"),
                            ("EUR", "Euro"),
                            ("USD", "US Dollar"),
                        ],
                        default="USD",
                        editable=False,
                        max_length=3,
                    ),
                ),
                (
                    "total_paid",
                    djmoney.models.fields.MoneyField(
                        decimal_places=2, default=Decimal("0"), max_digits=14
                    ),
                ),
                (
                    "total_interest_paid_currency",
                    djmoney.models.fields.CurrencyField(
                        choices=[
                            ("DOP", "Dominican Peso"),
                            ("EUR", "Euro"),
                            ("USD", "US Dollar"),
                        ],
                        default="USD",
                        editable=False,
                        max_length=3,
                    ),
                ),
                (
                    "total_interest_paid",
                    djmoney.models.fields.MoneyField(
                        decimal_places=2, default=Decimal("0"), max_digits=14
                    ),
                ),
                (
                    "late_fees_currency",
                    djmoney.models.fields.CurrencyField(
                        choices=[
                            ("DOP", "Dominican Peso"),
                            ("EUR", "Euro"),
                            ("USD", "US Dollar"),
                        ],
                        default="USD",
                        editable=False,
                        max_length=3,
                    ),
                ),
                (
                    "late_fees",
                    djmoney.models.fields.MoneyField(
                        decimal_places=2, default=Decimal("0"), max_digits=14
                    ),
                ),
                ("purpose", models.TextField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
                ("terms_accepted", models.BooleanField(default=False)),
                (
                    "contract_document",
                    models.FileField(
                        blank=True, null=True, upload_to="loan_contracts/"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="loans",
                        to="loans.customer",
                    ),
                ),
                (
                    "loan_officer",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="managed_loans",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "loans",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Collateral",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "collateral_type",
                    models.CharField(
                        choices=[
                            ("vehicle", "Vehicle"),
                            ("property", "Property/Real Estate"),
                            ("equipment", "Equipment"),
                            ("inventory", "Inventory"),
                            ("securities", "Securities/Stocks"),
                            ("cash_deposit", "Cash Deposit"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                ("description", models.TextField()),
                (
                    "estimated_value_currency",
                    djmoney.models.fields.CurrencyField(
                        choices=[
                            ("DOP", "Dominican Peso"),
                            ("EUR", "Euro"),
                            ("USD", "US Dollar"),
                        ],
                        default="USD",
                        editable=False,
                        max_length=3,
                    ),
                ),
                (
                    "estimated_value",
                    djmoney.models.fields.MoneyField(decimal_places=2, max_digits=14),
                ),
                (
                    "appraisal_value_currency",
                    djmoney.models.fields.CurrencyField(
                        choices=[
                            ("DOP", "Dominican Peso"),
                            ("EUR", "Euro"),
                            ("USD", "US Dollar"),
                        ],
                        default="USD",
                        editable=False,
                        max_length=3,
                        null=True,
                    ),
                ),
                (
                    "appraisal_value",
                    djmoney.models.fields.MoneyField(
                        blank=True, decimal_places=2, max_digits=14, null=True
                    ),
                ),
                ("appraisal_date", models.DateField(blank=True, null=True)),
                (
                    "documents",
                    models.FileField(
                        blank=True, null=True, upload_to="collateral_documents/"
                    ),
                ),
                (
                    "photos",
                    models.ImageField(
                        blank=True, null=True, upload_to="collateral_photos/"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("released", "Released"),
                            ("liquidated", "Liquidated"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "loan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="collaterals",
                        to="loans.loan",
                    ),
                ),
            ],
            options={
                "db_table": "loan_collaterals",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="LoanSchedule",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("installment_number", models.IntegerField()),
                ("due_date", models.DateField()),
                (
                    "total_amount_currency",
                    djmoney.models.fields.CurrencyField(
                        choices=[
                            ("DOP", "Dominican Peso"),
                            ("EUR", "Euro"),
                            ("USD", "US Dollar"),
                        ],
                        default="USD",
                        editable=False,
                        max_length=3,
                    ),
                ),
                (
                    "total_amount",
                    djmoney.models.fields.MoneyField(decimal_places=2, max_digits=14),
                ),
                (
                    "principal_amount_currency",
                    djmoney.models.fields.CurrencyField(
                        choices=[
                            ("DOP", "Dominican Peso"),
                            ("EUR", "Euro"),
                            ("USD", "US Dollar"),
                        ],
                        default="USD",
                        editable=False,
                        max_length=3,
                    ),
                ),
                (
                    "principal_amount",
                    djmoney.models.fields.MoneyField(decimal_places=2, max_digits=14),
                ),
                (
                    "interest_amount_currency",
                    djmoney.models.fields.CurrencyField(
                        choices=[
                            ("DOP", "Dominican Peso"),
                            ("EUR", "Euro"),
                            ("USD", "US Dollar"),
                        ],
                        default="USD",
                        editable=False,
                        max_length=3,
                    ),
                ),
                (
                    "interest_amount",
                    djmoney.models.fields.MoneyField(decimal_places=2, max_digits=14),
                ),
                (
                    "paid_amount_currency",
                    djmoney.models.fields.CurrencyField(
                        choices=[
                            ("DOP", "Dominican Peso"),
                            ("EUR", "Euro"),
                            ("USD", "US Dollar"),
                        ],
                        default="USD",
                        editable=False,
                        max_length=3,
                    ),
                ),
                (
                    "paid_amount",
                    djmoney.models.fields.MoneyField(
                        decimal_places=2, default=Decimal("0"), max_digits=14
                    ),
                ),
                ("paid_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("paid", "Paid"),
                            ("overdue", "Overdue"),
                            ("partial", "Partially Paid"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "loan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment_schedules",
                        to="loans.loan",
                    ),
                ),
            ],
            options={
                "db_table": "loan_schedules",
                "ordering": ["loan", "installment_number"],
            },
        ),
        migrations.CreateModel(
            name="LoanPayment",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "payment_number",
                    models.CharField(editable=False, max_length=50, unique=True),
                ),
                ("payment_date", models.DateField(default=django.utils.timezone.now)),
                (
                    "amount_currency",
                    djmoney.models.fields.CurrencyField(
                        choices=[
                            ("DOP", "Dominican Peso"),
                            ("EUR", "Euro"),
                            ("USD", "US Dollar"),
                        ],
                        default="USD",
                        editable=False,
                        max_length=3,
                    ),
                ),
                (
                    "amount",
                    djmoney.models.fields.MoneyField(
                        decimal_places=2,
                        max_digits=14,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                (
                    "principal_paid_currency",
                    djmoney.models.fields.CurrencyField(
                        choices=[
                            ("DOP", "Dominican Peso"),
                            ("EUR", "Euro"),
                            ("USD", "US Dollar"),
                        ],
                        default="USD",
                        editable=False,
                        max_length=3,
                    ),
                ),
                (
                    "principal_paid",
                    djmoney.models.fields.MoneyField(
                        decimal_places=2, default=Decimal("0"), max_digits=14
                    ),
                ),
                (
                    "interest_paid_currency",
                    djmoney.models.fields.CurrencyField(
                        choices=[
                            ("DOP", "Dominican Peso"),
                            ("EUR", "Euro"),
                            ("USD", "US Dollar"),
                        ],
                        default="USD",
                        editable=False,
                        max_length=3,
                    ),
                ),
                (
                    "interest_paid",
                    djmoney.models.fields.MoneyField(
                        decimal_places=2, default=Decimal("0"), max_digits=14
                    ),
                ),
                (
                    "late_fee_paid_currency",
                    djmoney.models.fields.CurrencyField(
                        choices=[
                            ("DOP", "Dominican Peso"),
                            ("EUR", "Euro"),
                            ("USD", "US Dollar"),
                        ],
                        default="USD",
                        editable=False,
                        max_length=3,
                    ),
                ),
                (
                    "late_fee_paid",
                    djmoney.models.fields.MoneyField(
                        decimal_places=2, default=Decimal("0"), max_digits=14
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("cash", "Cash"),
                            ("check", "Check"),
                            ("bank_transfer", "Bank Transfer"),
                            ("card", "Credit/Debit Card"),
                            ("mobile_payment", "Mobile Payment"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "reference_number",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("reversed", "Reversed"),
                        ],
                        default="completed",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "receipt",
                    models.FileField(
                        blank=True, null=True, upload_to="payment_receipts/"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "loan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payments",
                        to="loans.loan",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "schedule",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="payments",
                        to="loans.loanschedule",
                    ),
                ),
            ],
            options={
                "db_table": "loan_payments",
                "ordering": ["-payment_date", "-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="customer",
            index=models.Index(
                fields=["customer_id"], name="customers_custome_b85ebb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="customer",
            index=models.Index(
                fields=["id_number"], name="customers_id_numb_407e10_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="customer",
            index=models.Index(fields=["email"], name="customers_email_92e882_idx"),
        ),
        migrations.AddIndex(
            model_name="loan",
            index=models.Index(fields=["loan_number"], name="loans_loan_nu_a48674_idx"),
        ),
        migrations.AddIndex(
            model_name="loan",
            index=models.Index(fields=["status"], name="loans_status_9049a0_idx"),
        ),
        migrations.AddIndex(
            model_name="loan",
            index=models.Index(fields=["customer"], name="loans_custome_2d1850_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="loanschedule",
            unique_together={("loan", "installment_number")},
        ),
        migrations.AddIndex(
            model_name="loanpayment",
            index=models.Index(
                fields=["payment_number"], name="loan_paymen_payment_bcbff9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="loanpayment",
            index=models.Index(fields=["loan"], name="loan_paymen_loan_id_d7ceb4_idx"),
        ),
        migrations.AddIndex(
            model_name="loanpayment",
            index=models.Index(
                fields=["payment_date"], name="loan_paymen_payment_c96c3b_idx"
            ),
        ),
    ]
