# Generated by Django 5.0.9 on 2025-10-29 19:55

import django.db.models.deletion
import djmoney.models.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loans", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="loan",
            name="approval_notes",
            field=models.TextField(
                blank=True, help_text="Notes from approval/rejection", null=True
            ),
        ),
        migrations.AddField(
            model_name="loan",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who approved this loan",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approved_loans",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="loan",
            name="rejected_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who rejected this loan",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="rejected_loans",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="loan",
            name="rejection_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="loan",
            name="principal_amount",
            field=djmoney.models.fields.MoneyField(decimal_places=2, max_digits=14),
        ),
        migrations.AlterField(
            model_name="loanpayment",
            name="amount",
            field=djmoney.models.fields.MoneyField(decimal_places=2, max_digits=14),
        ),
    ]
