# Generated by Django 5.0.9 on 2025-10-30 02:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loans", "0002_loan_approval_notes_loan_approved_by_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomerDocument",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("id_card", "ID Card / Cédula"),
                            ("passport", "Passport"),
                            ("drivers_license", "Driver's License"),
                            ("proof_of_income", "Proof of Income"),
                            ("bank_statement", "Bank Statement"),
                            ("proof_of_address", "Proof of Address"),
                            ("employment_letter", "Employment Letter"),
                            ("tax_return", "Tax Return"),
                            ("business_license", "Business License"),
                            ("utility_bill", "Utility Bill"),
                            ("contract", "Contract / Agreement"),
                            ("other", "Other Document"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Document title or description", max_length=200
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "document_file",
                    models.FileField(
                        help_text="Upload document file (PDF, JPG, PNG, etc.)",
                        upload_to="customer_documents/%Y/%m/",
                    ),
                ),
                (
                    "file_size",
                    models.IntegerField(
                        blank=True, help_text="File size in bytes", null=True
                    ),
                ),
                (
                    "file_type",
                    models.CharField(
                        blank=True,
                        help_text="MIME type of the file",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "verification_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Verification"),
                            ("verified", "Verified"),
                            ("rejected", "Rejected"),
                            ("expired", "Expired"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                (
                    "rejection_reason",
                    models.TextField(
                        blank=True,
                        help_text="Reason for rejection if status is rejected",
                        null=True,
                    ),
                ),
                (
                    "issue_date",
                    models.DateField(
                        blank=True, help_text="Document issue/creation date", null=True
                    ),
                ),
                (
                    "expiry_date",
                    models.DateField(
                        blank=True,
                        help_text="Document expiration date (if applicable)",
                        null=True,
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "is_primary",
                    models.BooleanField(
                        default=False, help_text="Mark as primary document of this type"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="loans.customer",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "verified_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who verified this document",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="verified_documents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "customer_documents",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["customer", "document_type"],
                        name="customer_do_custome_a544ca_idx",
                    ),
                    models.Index(
                        fields=["verification_status"],
                        name="customer_do_verific_a49f86_idx",
                    ),
                    models.Index(
                        fields=["expiry_date"], name="customer_do_expiry__efb805_idx"
                    ),
                ],
            },
        ),
    ]
