# Generated by Django 5.0.9 on 2025-10-30 17:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("loans", "0004_add_collection_features"),
    ]

    operations = [
        # Add timestamp fields to CollectionContact
        migrations.AddField(
            model_name='collectioncontact',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='collectioncontact',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        # Add timestamp fields to CollectionReminder
        migrations.AddField(
            model_name='collectionreminder',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='collectionreminder',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
