# Generated by Django 5.0.9 on 2025-10-31 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loans", "0004_add_collection_features"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="id_type",
            field=models.CharField(
                choices=[
                    ("cedula", "Cédula"),
                    ("rnc", "RNC (Registro Nacional de Contribuyentes)"),
                    ("nss", "NSS (Número de Seguridad Social)"),
                    ("ncf", "NCF (Número de Comprobante Fiscal)"),
                    ("passport", "Passport"),
                    ("driver_license", "Driver License"),
                ],
                max_length=50,
            ),
        ),
    ]
