# Generated by Django 5.0.9 on 2025-11-01 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loans", "0006_alter_customer_id_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="loan",
            name="interest_type",
            field=models.CharField(
                choices=[
                    ("fixed", "Fixed Interest Rate"),
                    ("variable", "Variable Interest Rate"),
                ],
                default="fixed",
                help_text="Type of interest rate (fixed or variable)",
                max_length=20,
            ),
        ),
    ]
