# Generated by Django 5.0.9 on 2025-11-01 05:02

from django.db import migrations, models


def update_draft_to_pending(apps, schema_editor):
    """Update all loans with status 'draft' to 'pending'"""
    Loan = apps.get_model('loans', 'Loan')
    # Update all draft loans to pending
    Loan.objects.filter(status='draft').update(status='pending')


def reverse_pending_to_draft(apps, schema_editor):
    """Reverse: Update all loans with status 'pending' back to 'draft'"""
    # This is only for rollback purposes - we won't actually use this
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("loans", "0007_loan_interest_type"),
    ]

    operations = [
        # First, update existing draft loans to pending
        migrations.RunPython(update_draft_to_pending, reverse_pending_to_draft),
        # Then, alter the field to remove draft from choices
        migrations.AlterField(
            model_name="loan",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending Approval"),
                    ("approved", "Approved"),
                    ("active", "Active"),
                    ("paid", "Paid Off"),
                    ("defaulted", "Defaulted"),
                    ("written_off", "Written Off"),
                    ("rejected", "Rejected"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
