# Generated by Django 5.0.9 on 2025-11-01 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loans", "0008_remove_draft_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="loan",
            name="interest_type",
            field=models.CharField(
                choices=[
                    ("fixed", "Fixed Interest Rate"),
                    ("variable", "Variable Interest Rate"),
                    ("variable_rd", "Variable (RD) - Direct Rate per Period"),
                ],
                default="fixed",
                help_text="Type of interest rate (fixed, variable, or variable_rd)",
                max_length=20,
            ),
        ),
    ]
