# Generated by Django 5.0.9 on 2025-11-02 22:37

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loans", "0009_add_variable_rd_interest_type"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ContractTemplate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Template name (e.g., 'Personal Loan Contract', 'Business Loan Agreement')",
                        max_length=200,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Description of when to use this template"
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        help_text="\n    Available variables (use {{variable_name}} in template):\n    - {{customer_name}}: Full name of customer\n    - {{customer_id}}: Customer ID number\n    - {{customer_id_number}}: Customer cedula/ID\n    - {{customer_address}}: Full customer address\n    - {{customer_phone}}: Customer phone number\n    - {{customer_email}}: Customer email\n    - {{loan_number}}: Loan number (e.g., LN-2025-ABC123)\n    - {{loan_amount}}: Principal loan amount\n    - {{loan_amount_words}}: Loan amount in words\n    - {{interest_rate}}: Annual interest rate\n    - {{loan_term}}: Loan term in months\n    - {{payment_frequency}}: Payment frequency (weekly, biweekly, monthly)\n    - {{monthly_payment}}: Monthly payment amount\n    - {{total_amount}}: Total amount to be repaid\n    - {{disbursement_date}}: Date loan was disbursed\n    - {{first_payment_date}}: Date of first payment\n    - {{final_payment_date}}: Date of final payment\n    - {{loan_officer}}: Name of loan officer\n    - {{company_name}}: Tenant company name\n    - {{company_address}}: Tenant address\n    - {{company_phone}}: Tenant phone\n    - {{company_email}}: Tenant email\n    - {{contract_date}}: Date contract was generated\n    - {{guarantor_name}}: Guarantor name (if applicable)\n    - {{guarantor_id}}: Guarantor ID (if applicable)\n    - {{collateral_description}}: Description of collaterals\n    "
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Only active templates can be used to generate contracts",
                    ),
                ),
                (
                    "is_default",
                    models.BooleanField(
                        default=False, help_text="Default template for new contracts"
                    ),
                ),
                (
                    "loan_types",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Loan types this template applies to (empty = all types)",
                    ),
                ),
                (
                    "header_image",
                    models.ImageField(
                        blank=True,
                        help_text="Optional header image/logo for contract",
                        null=True,
                        upload_to="contract_templates/headers/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                ["jpg", "jpeg", "png"]
                            )
                        ],
                    ),
                ),
                (
                    "footer_text",
                    models.TextField(
                        blank=True,
                        help_text="Optional footer text (terms, conditions, etc.)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_contract_templates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "contract_templates",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Contract",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "contract_number",
                    models.CharField(
                        help_text="Unique contract number (e.g., CONT-2025-ABC123)",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        help_text="Rendered contract content with all variables replaced"
                    ),
                ),
                (
                    "pdf_file",
                    models.FileField(
                        blank=True,
                        help_text="Generated PDF version of the contract",
                        null=True,
                        upload_to="contracts/pdfs/",
                        validators=[
                            django.core.validators.FileExtensionValidator(["pdf"])
                        ],
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("pending_signature", "Pending Signature"),
                            ("signed", "Signed"),
                            ("active", "Active"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "customer_signed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When customer signed the contract",
                        null=True,
                    ),
                ),
                (
                    "customer_signature",
                    models.ImageField(
                        blank=True,
                        help_text="Customer signature image",
                        null=True,
                        upload_to="contracts/signatures/customers/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                ["jpg", "jpeg", "png"]
                            )
                        ],
                    ),
                ),
                (
                    "officer_signed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When loan officer signed the contract",
                        null=True,
                    ),
                ),
                (
                    "officer_signature",
                    models.ImageField(
                        blank=True,
                        help_text="Loan officer signature image",
                        null=True,
                        upload_to="contracts/signatures/officers/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                ["jpg", "jpeg", "png"]
                            )
                        ],
                    ),
                ),
                ("witness_name", models.CharField(blank=True, max_length=200)),
                ("witness_id", models.CharField(blank=True, max_length=50)),
                (
                    "witness_signature",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="contracts/signatures/witnesses/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                ["jpg", "jpeg", "png"]
                            )
                        ],
                    ),
                ),
                ("witness_signed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "special_terms",
                    models.TextField(
                        blank=True,
                        help_text="Any special terms or conditions added to this contract",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Internal notes about this contract"
                    ),
                ),
                ("generated_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "generated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="generated_contracts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "loan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contracts",
                        to="loans.loan",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        help_text="Template used to generate this contract",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="generated_contracts",
                        to="loans.contracttemplate",
                    ),
                ),
            ],
            options={
                "db_table": "contracts",
                "ordering": ["-generated_at"],
            },
        ),
        migrations.AddIndex(
            model_name="contracttemplate",
            index=models.Index(
                fields=["is_active", "is_default"],
                name="contract_te_is_acti_3a6efc_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="contracttemplate",
            index=models.Index(
                fields=["created_at"], name="contract_te_created_07a345_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="contract",
            index=models.Index(
                fields=["contract_number"], name="contracts_contrac_bb0c23_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="contract",
            index=models.Index(
                fields=["loan", "status"], name="contracts_loan_id_f96389_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="contract",
            index=models.Index(fields=["status"], name="contracts_status_093df1_idx"),
        ),
        migrations.AddIndex(
            model_name="contract",
            index=models.Index(
                fields=["generated_at"], name="contracts_generat_0165df_idx"
            ),
        ),
    ]
