# Generated by Django 5.0.9 on 2025-11-03 02:31

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loans", "0010_contracttemplate_contract_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContractSignatureToken",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("token", models.CharField(db_index=True, max_length=64, unique=True)),
                (
                    "email",
                    models.EmailField(
                        help_text="Email address where the signature link was sent",
                        max_length=254,
                    ),
                ),
                ("can_sign_as_customer", models.BooleanField(default=True)),
                ("can_sign_as_officer", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "expires_at",
                    models.DateTimeField(help_text="When this token expires"),
                ),
                (
                    "used_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the token was used to sign",
                        null=True,
                    ),
                ),
                (
                    "sent_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When the email was sent"
                    ),
                ),
                (
                    "contract",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="signature_tokens",
                        to="loans.contract",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["token"], name="loans_contr_token_0becb9_idx"),
                    models.Index(
                        fields=["contract", "email"],
                        name="loans_contr_contrac_a781a5_idx",
                    ),
                ],
            },
        ),
    ]
