# Generated by Django 5.0.9 on 2025-11-03 04:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loans", "0011_contractsignaturetoken"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="contract",
            name="archived_at",
            field=models.DateTimeField(
                blank=True, help_text="When this contract was archived", null=True
            ),
        ),
        migrations.AddField(
            model_name="contract",
            name="archived_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who archived this contract",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="archived_contracts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="contract",
            name="is_archived",
            field=models.BooleanField(
                default=False, help_text="Whether this contract has been archived"
            ),
        ),
    ]
