# Generated by Django 5.0.9 on 2025-12-13 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loans", "0012_contract_archived_at_contract_archived_by_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="collateral",
            name="metadata",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
