# Generated by Django 5.0.9 on 2025-12-13 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loans", "0013_add_metadata_to_collateral"),
    ]

    operations = [
        migrations.AlterField(
            model_name="collateral",
            name="description",
            field=models.TextField(blank=True, default=""),
        ),
    ]
