# Generated by Django 5.0.9 on 2026-03-29 22:01

import djmoney.models.fields
from decimal import Decimal
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("loans", "0014_make_collateral_description_optional"),
    ]

    operations = [
        migrations.AlterField(
            model_name="collateral",
            name="appraisal_value",
            field=djmoney.models.fields.MoneyField(
                blank=True,
                decimal_places=2,
                default_currency="USD",
                max_digits=14,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="collateral",
            name="estimated_value",
            field=djmoney.models.fields.MoneyField(
                decimal_places=2, default_currency="USD", max_digits=14
            ),
        ),
        migrations.AlterField(
            model_name="collectioncontact",
            name="promise_amount",
            field=djmoney.models.fields.MoneyField(
                blank=True,
                decimal_places=2,
                default_currency="USD",
                max_digits=12,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="monthly_income",
            field=djmoney.models.fields.MoneyField(
                blank=True,
                decimal_places=2,
                default_currency="USD",
                max_digits=14,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="loan",
            name="late_fees",
            field=djmoney.models.fields.MoneyField(
                decimal_places=2,
                default=Decimal("0"),
                default_currency="USD",
                max_digits=14,
            ),
        ),
        migrations.AlterField(
            model_name="loan",
            name="outstanding_balance",
            field=djmoney.models.fields.MoneyField(
                decimal_places=2,
                default=Decimal("0"),
                default_currency="USD",
                max_digits=14,
            ),
        ),
        migrations.AlterField(
            model_name="loan",
            name="payment_amount",
            field=djmoney.models.fields.MoneyField(
                decimal_places=2,
                default_currency="USD",
                help_text="Regular payment amount",
                max_digits=14,
            ),
        ),
        migrations.AlterField(
            model_name="loan",
            name="principal_amount",
            field=djmoney.models.fields.MoneyField(
                decimal_places=2, default_currency="USD", max_digits=14
            ),
        ),
        migrations.AlterField(
            model_name="loan",
            name="total_interest_paid",
            field=djmoney.models.fields.MoneyField(
                decimal_places=2,
                default=Decimal("0"),
                default_currency="USD",
                max_digits=14,
            ),
        ),
        migrations.AlterField(
            model_name="loan",
            name="total_paid",
            field=djmoney.models.fields.MoneyField(
                decimal_places=2,
                default=Decimal("0"),
                default_currency="USD",
                max_digits=14,
            ),
        ),
        migrations.AlterField(
            model_name="loanpayment",
            name="amount",
            field=djmoney.models.fields.MoneyField(
                decimal_places=2, default_currency="USD", max_digits=14
            ),
        ),
        migrations.AlterField(
            model_name="loanpayment",
            name="interest_paid",
            field=djmoney.models.fields.MoneyField(
                decimal_places=2,
                default=Decimal("0"),
                default_currency="USD",
                max_digits=14,
            ),
        ),
        migrations.AlterField(
            model_name="loanpayment",
            name="late_fee_paid",
            field=djmoney.models.fields.MoneyField(
                decimal_places=2,
                default=Decimal("0"),
                default_currency="USD",
                max_digits=14,
            ),
        ),
        migrations.AlterField(
            model_name="loanpayment",
            name="principal_paid",
            field=djmoney.models.fields.MoneyField(
                decimal_places=2,
                default=Decimal("0"),
                default_currency="USD",
                max_digits=14,
            ),
        ),
        migrations.AlterField(
            model_name="loanschedule",
            name="interest_amount",
            field=djmoney.models.fields.MoneyField(
                decimal_places=2, default_currency="USD", max_digits=14
            ),
        ),
        migrations.AlterField(
            model_name="loanschedule",
            name="late_fee_amount",
            field=djmoney.models.fields.MoneyField(
                decimal_places=2,
                default=Decimal("0.00"),
                default_currency="USD",
                help_text="Monto de mora acumulado",
                max_digits=14,
            ),
        ),
        migrations.AlterField(
            model_name="loanschedule",
            name="late_fee_paid",
            field=djmoney.models.fields.MoneyField(
                decimal_places=2,
                default=Decimal("0.00"),
                default_currency="USD",
                help_text="Mora pagada",
                max_digits=14,
            ),
        ),
        migrations.AlterField(
            model_name="loanschedule",
            name="paid_amount",
            field=djmoney.models.fields.MoneyField(
                decimal_places=2,
                default=Decimal("0"),
                default_currency="USD",
                max_digits=14,
            ),
        ),
        migrations.AlterField(
            model_name="loanschedule",
            name="principal_amount",
            field=djmoney.models.fields.MoneyField(
                decimal_places=2, default_currency="USD", max_digits=14
            ),
        ),
        migrations.AlterField(
            model_name="loanschedule",
            name="total_amount",
            field=djmoney.models.fields.MoneyField(
                decimal_places=2, default_currency="USD", max_digits=14
            ),
        ),
    ]
