# Generated by Django 5.0.9 on 2026-03-31 21:44

import django.db.models.deletion
import djmoney.models.fields
import phonenumber_field.modelfields
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loans", "0015_alter_collateral_appraisal_value_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="collateral",
            name="appraisal_value",
            field=djmoney.models.fields.MoneyField(
                blank=True, decimal_places=2, max_digits=14, null=True
            ),
        ),
        migrations.AlterField(
            model_name="collateral",
            name="appraisal_value_currency",
            field=djmoney.models.fields.CurrencyField(
                choices=[
                    ("DOP", "Dominican Peso"),
                    ("EUR", "Euro"),
                    ("USD", "US Dollar"),
                ],
                default="DOP",
                editable=False,
                max_length=3,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="collateral",
            name="estimated_value",
            field=djmoney.models.fields.MoneyField(decimal_places=2, max_digits=14),
        ),
        migrations.AlterField(
            model_name="collateral",
            name="estimated_value_currency",
            field=djmoney.models.fields.CurrencyField(
                choices=[
                    ("DOP", "Dominican Peso"),
                    ("EUR", "Euro"),
                    ("USD", "US Dollar"),
                ],
                default="DOP",
                editable=False,
                max_length=3,
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="monthly_income",
            field=djmoney.models.fields.MoneyField(
                blank=True, decimal_places=2, max_digits=14, null=True
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="monthly_income_currency",
            field=djmoney.models.fields.CurrencyField(
                choices=[
                    ("DOP", "Dominican Peso"),
                    ("EUR", "Euro"),
                    ("USD", "US Dollar"),
                ],
                default="DOP",
                editable=False,
                max_length=3,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="loan",
            name="late_fees",
            field=djmoney.models.fields.MoneyField(
                decimal_places=2, default=Decimal("0"), max_digits=14
            ),
        ),
        migrations.AlterField(
            model_name="loan",
            name="late_fees_currency",
            field=djmoney.models.fields.CurrencyField(
                choices=[
                    ("DOP", "Dominican Peso"),
                    ("EUR", "Euro"),
                    ("USD", "US Dollar"),
                ],
                default="DOP",
                editable=False,
                max_length=3,
            ),
        ),
        migrations.AlterField(
            model_name="loan",
            name="outstanding_balance",
            field=djmoney.models.fields.MoneyField(
                decimal_places=2, default=Decimal("0"), max_digits=14
            ),
        ),
        migrations.AlterField(
            model_name="loan",
            name="outstanding_balance_currency",
            field=djmoney.models.fields.CurrencyField(
                choices=[
                    ("DOP", "Dominican Peso"),
                    ("EUR", "Euro"),
                    ("USD", "US Dollar"),
                ],
                default="DOP",
                editable=False,
                max_length=3,
            ),
        ),
        migrations.AlterField(
            model_name="loan",
            name="payment_amount",
            field=djmoney.models.fields.MoneyField(
                decimal_places=2, help_text="Regular payment amount", max_digits=14
            ),
        ),
        migrations.AlterField(
            model_name="loan",
            name="payment_amount_currency",
            field=djmoney.models.fields.CurrencyField(
                choices=[
                    ("DOP", "Dominican Peso"),
                    ("EUR", "Euro"),
                    ("USD", "US Dollar"),
                ],
                default="DOP",
                editable=False,
                max_length=3,
            ),
        ),
        migrations.AlterField(
            model_name="loan",
            name="principal_amount",
            field=djmoney.models.fields.MoneyField(decimal_places=2, max_digits=14),
        ),
        migrations.AlterField(
            model_name="loan",
            name="principal_amount_currency",
            field=djmoney.models.fields.CurrencyField(
                choices=[
                    ("DOP", "Dominican Peso"),
                    ("EUR", "Euro"),
                    ("USD", "US Dollar"),
                ],
                default="DOP",
                editable=False,
                max_length=3,
            ),
        ),
        migrations.AlterField(
            model_name="loan",
            name="total_interest_paid",
            field=djmoney.models.fields.MoneyField(
                decimal_places=2, default=Decimal("0"), max_digits=14
            ),
        ),
        migrations.AlterField(
            model_name="loan",
            name="total_interest_paid_currency",
            field=djmoney.models.fields.CurrencyField(
                choices=[
                    ("DOP", "Dominican Peso"),
                    ("EUR", "Euro"),
                    ("USD", "US Dollar"),
                ],
                default="DOP",
                editable=False,
                max_length=3,
            ),
        ),
        migrations.AlterField(
            model_name="loan",
            name="total_paid",
            field=djmoney.models.fields.MoneyField(
                decimal_places=2, default=Decimal("0"), max_digits=14
            ),
        ),
        migrations.AlterField(
            model_name="loan",
            name="total_paid_currency",
            field=djmoney.models.fields.CurrencyField(
                choices=[
                    ("DOP", "Dominican Peso"),
                    ("EUR", "Euro"),
                    ("USD", "US Dollar"),
                ],
                default="DOP",
                editable=False,
                max_length=3,
            ),
        ),
        migrations.AlterField(
            model_name="loanpayment",
            name="amount",
            field=djmoney.models.fields.MoneyField(decimal_places=2, max_digits=14),
        ),
        migrations.AlterField(
            model_name="loanpayment",
            name="amount_currency",
            field=djmoney.models.fields.CurrencyField(
                choices=[
                    ("DOP", "Dominican Peso"),
                    ("EUR", "Euro"),
                    ("USD", "US Dollar"),
                ],
                default="DOP",
                editable=False,
                max_length=3,
            ),
        ),
        migrations.AlterField(
            model_name="loanpayment",
            name="interest_paid",
            field=djmoney.models.fields.MoneyField(
                decimal_places=2, default=Decimal("0"), max_digits=14
            ),
        ),
        migrations.AlterField(
            model_name="loanpayment",
            name="interest_paid_currency",
            field=djmoney.models.fields.CurrencyField(
                choices=[
                    ("DOP", "Dominican Peso"),
                    ("EUR", "Euro"),
                    ("USD", "US Dollar"),
                ],
                default="DOP",
                editable=False,
                max_length=3,
            ),
        ),
        migrations.AlterField(
            model_name="loanpayment",
            name="late_fee_paid",
            field=djmoney.models.fields.MoneyField(
                decimal_places=2, default=Decimal("0"), max_digits=14
            ),
        ),
        migrations.AlterField(
            model_name="loanpayment",
            name="late_fee_paid_currency",
            field=djmoney.models.fields.CurrencyField(
                choices=[
                    ("DOP", "Dominican Peso"),
                    ("EUR", "Euro"),
                    ("USD", "US Dollar"),
                ],
                default="DOP",
                editable=False,
                max_length=3,
            ),
        ),
        migrations.AlterField(
            model_name="loanpayment",
            name="principal_paid",
            field=djmoney.models.fields.MoneyField(
                decimal_places=2, default=Decimal("0"), max_digits=14
            ),
        ),
        migrations.AlterField(
            model_name="loanpayment",
            name="principal_paid_currency",
            field=djmoney.models.fields.CurrencyField(
                choices=[
                    ("DOP", "Dominican Peso"),
                    ("EUR", "Euro"),
                    ("USD", "US Dollar"),
                ],
                default="DOP",
                editable=False,
                max_length=3,
            ),
        ),
        migrations.AlterField(
            model_name="loanschedule",
            name="interest_amount",
            field=djmoney.models.fields.MoneyField(decimal_places=2, max_digits=14),
        ),
        migrations.AlterField(
            model_name="loanschedule",
            name="interest_amount_currency",
            field=djmoney.models.fields.CurrencyField(
                choices=[
                    ("DOP", "Dominican Peso"),
                    ("EUR", "Euro"),
                    ("USD", "US Dollar"),
                ],
                default="DOP",
                editable=False,
                max_length=3,
            ),
        ),
        migrations.AlterField(
            model_name="loanschedule",
            name="late_fee_amount",
            field=djmoney.models.fields.MoneyField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Monto de mora acumulado",
                max_digits=14,
            ),
        ),
        migrations.AlterField(
            model_name="loanschedule",
            name="late_fee_amount_currency",
            field=djmoney.models.fields.CurrencyField(
                choices=[
                    ("DOP", "Dominican Peso"),
                    ("EUR", "Euro"),
                    ("USD", "US Dollar"),
                ],
                default="DOP",
                editable=False,
                max_length=3,
            ),
        ),
        migrations.AlterField(
            model_name="loanschedule",
            name="late_fee_paid",
            field=djmoney.models.fields.MoneyField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Mora pagada",
                max_digits=14,
            ),
        ),
        migrations.AlterField(
            model_name="loanschedule",
            name="late_fee_paid_currency",
            field=djmoney.models.fields.CurrencyField(
                choices=[
                    ("DOP", "Dominican Peso"),
                    ("EUR", "Euro"),
                    ("USD", "US Dollar"),
                ],
                default="DOP",
                editable=False,
                max_length=3,
            ),
        ),
        migrations.AlterField(
            model_name="loanschedule",
            name="paid_amount",
            field=djmoney.models.fields.MoneyField(
                decimal_places=2, default=Decimal("0"), max_digits=14
            ),
        ),
        migrations.AlterField(
            model_name="loanschedule",
            name="paid_amount_currency",
            field=djmoney.models.fields.CurrencyField(
                choices=[
                    ("DOP", "Dominican Peso"),
                    ("EUR", "Euro"),
                    ("USD", "US Dollar"),
                ],
                default="DOP",
                editable=False,
                max_length=3,
            ),
        ),
        migrations.AlterField(
            model_name="loanschedule",
            name="principal_amount",
            field=djmoney.models.fields.MoneyField(decimal_places=2, max_digits=14),
        ),
        migrations.AlterField(
            model_name="loanschedule",
            name="principal_amount_currency",
            field=djmoney.models.fields.CurrencyField(
                choices=[
                    ("DOP", "Dominican Peso"),
                    ("EUR", "Euro"),
                    ("USD", "US Dollar"),
                ],
                default="DOP",
                editable=False,
                max_length=3,
            ),
        ),
        migrations.AlterField(
            model_name="loanschedule",
            name="total_amount",
            field=djmoney.models.fields.MoneyField(decimal_places=2, max_digits=14),
        ),
        migrations.AlterField(
            model_name="loanschedule",
            name="total_amount_currency",
            field=djmoney.models.fields.CurrencyField(
                choices=[
                    ("DOP", "Dominican Peso"),
                    ("EUR", "Euro"),
                    ("USD", "US Dollar"),
                ],
                default="DOP",
                editable=False,
                max_length=3,
            ),
        ),
        migrations.CreateModel(
            name="CollectorVisit",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("latitude", models.DecimalField(decimal_places=7, max_digits=10)),
                ("longitude", models.DecimalField(decimal_places=7, max_digits=10)),
                (
                    "accuracy",
                    models.FloatField(
                        blank=True, help_text="GPS accuracy in meters", null=True
                    ),
                ),
                (
                    "altitude",
                    models.FloatField(
                        blank=True, help_text="Altitude in meters", null=True
                    ),
                ),
                (
                    "visit_type",
                    models.CharField(
                        choices=[
                            ("collection", "Cobro"),
                            ("followup", "Seguimiento"),
                            ("verification", "Verificación"),
                            ("delivery", "Entrega documento"),
                            ("check_in", "Check-in"),
                        ],
                        default="collection",
                        max_length=20,
                    ),
                ),
                (
                    "outcome",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("payment_collected", "Pago cobrado"),
                            ("promise_to_pay", "Promesa de pago"),
                            ("not_home", "No se encontró"),
                            ("refused", "Se negó a pagar"),
                            ("partial_payment", "Pago parcial"),
                            ("rescheduled", "Reprogramado"),
                            ("other", "Otro"),
                        ],
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "amount_collected",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Amount collected during visit (if any)",
                        max_digits=14,
                        null=True,
                    ),
                ),
                (
                    "promise_date",
                    models.DateField(
                        blank=True, help_text="Date customer promised to pay", null=True
                    ),
                ),
                (
                    "promise_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=14, null=True
                    ),
                ),
                (
                    "photo",
                    models.ImageField(
                        blank=True,
                        help_text="Photo evidence of visit",
                        null=True,
                        upload_to="collector_visits/photos/",
                    ),
                ),
                ("checked_in_at", models.DateTimeField(auto_now_add=True)),
                ("checked_out_at", models.DateTimeField(blank=True, null=True)),
                (
                    "collector",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="collector_visits",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="collector_visits",
                        to="loans.customer",
                    ),
                ),
                (
                    "loan",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="collector_visits",
                        to="loans.loan",
                    ),
                ),
                (
                    "schedule",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="collector_visits",
                        to="loans.loanschedule",
                    ),
                ),
            ],
            options={
                "db_table": "loan_collector_visits",
                "ordering": ["-checked_in_at"],
            },
        ),
        migrations.CreateModel(
            name="Guarantor",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                (
                    "id_type",
                    models.CharField(
                        choices=[
                            ("cedula", "Cédula"),
                            ("passport", "Pasaporte"),
                            ("rnc", "RNC"),
                        ],
                        max_length=20,
                    ),
                ),
                ("id_number", models.CharField(max_length=50)),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[("M", "Masculino"), ("F", "Femenino")],
                        max_length=1,
                    ),
                ),
                (
                    "phone",
                    phonenumber_field.modelfields.PhoneNumberField(
                        max_length=128, region=None
                    ),
                ),
                (
                    "alternate_phone",
                    phonenumber_field.modelfields.PhoneNumberField(
                        blank=True, max_length=128, null=True, region=None
                    ),
                ),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("address", models.TextField()),
                ("city", models.CharField(blank=True, max_length=100)),
                ("province", models.CharField(blank=True, max_length=100)),
                ("employer_name", models.CharField(blank=True, max_length=200)),
                ("occupation", models.CharField(blank=True, max_length=100)),
                (
                    "monthly_income_currency",
                    djmoney.models.fields.CurrencyField(
                        choices=[
                            ("DOP", "Dominican Peso"),
                            ("EUR", "Euro"),
                            ("USD", "US Dollar"),
                        ],
                        default="DOP",
                        editable=False,
                        max_length=3,
                        null=True,
                    ),
                ),
                (
                    "monthly_income",
                    djmoney.models.fields.MoneyField(
                        blank=True, decimal_places=2, max_digits=14, null=True
                    ),
                ),
                (
                    "relationship",
                    models.CharField(
                        choices=[
                            ("spouse", "Cónyuge"),
                            ("parent", "Padre/Madre"),
                            ("sibling", "Hermano/a"),
                            ("friend", "Amigo/a"),
                            ("business_partner", "Socio"),
                            ("coworker", "Compañero trabajo"),
                            ("other", "Otro"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "id_document",
                    models.FileField(
                        blank=True, null=True, upload_to="guarantor_documents/ids/"
                    ),
                ),
                (
                    "proof_of_income",
                    models.FileField(
                        blank=True, null=True, upload_to="guarantor_documents/income/"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Activo"),
                            ("released", "Liberado"),
                            ("defaulted", "En mora"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "loan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="guarantors",
                        to="loans.loan",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "loan_guarantors",
                "ordering": ["loan", "last_name"],
            },
        ),
        migrations.CreateModel(
            name="CollectorLocation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("latitude", models.DecimalField(decimal_places=7, max_digits=10)),
                ("longitude", models.DecimalField(decimal_places=7, max_digits=10)),
                ("accuracy", models.FloatField(blank=True, null=True)),
                (
                    "speed",
                    models.FloatField(blank=True, help_text="Speed in m/s", null=True),
                ),
                (
                    "heading",
                    models.FloatField(
                        blank=True, help_text="Heading in degrees", null=True
                    ),
                ),
                (
                    "battery_level",
                    models.IntegerField(
                        blank=True, help_text="Device battery %", null=True
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "collector",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gps_locations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "loan_collector_locations",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["collector", "-timestamp"],
                        name="loan_collec_collect_32570b_idx",
                    )
                ],
            },
        ),
    ]
