# Generated by Django 5.0.9 on 2026-04-03 20:42

import django.db.models.deletion
import phonenumber_field.modelfields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loans", "0016_alter_collateral_appraisal_value_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomerEmail",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                (
                    "email_type",
                    models.CharField(
                        choices=[
                            ("personal", "Personal"),
                            ("work", "Trabajo"),
                            ("business", "Empresa"),
                            ("other", "Otro"),
                        ],
                        default="personal",
                        max_length=20,
                    ),
                ),
                ("label", models.CharField(blank=True, max_length=50)),
                ("is_primary", models.BooleanField(default=False)),
                ("notes", models.CharField(blank=True, max_length=200)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="email_addresses",
                        to="loans.customer",
                    ),
                ),
            ],
            options={
                "db_table": "customer_emails",
                "ordering": ["-is_primary", "email_type"],
            },
        ),
        migrations.CreateModel(
            name="CustomerPhone",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "phone",
                    phonenumber_field.modelfields.PhoneNumberField(
                        max_length=128, region=None
                    ),
                ),
                (
                    "phone_type",
                    models.CharField(
                        choices=[
                            ("mobile", "Celular"),
                            ("home", "Casa"),
                            ("work", "Oficina"),
                            ("landline", "Fijo"),
                            ("whatsapp", "WhatsApp"),
                            ("fax", "Fax"),
                            ("other", "Otro"),
                        ],
                        default="mobile",
                        max_length=20,
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        blank=True,
                        help_text='Etiqueta personalizada (ej: "Celular esposa", "Oficina 2do piso")',
                        max_length=50,
                    ),
                ),
                ("is_primary", models.BooleanField(default=False)),
                (
                    "is_whatsapp",
                    models.BooleanField(
                        default=False, help_text="Este número tiene WhatsApp"
                    ),
                ),
                ("notes", models.CharField(blank=True, max_length=200)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="phone_numbers",
                        to="loans.customer",
                    ),
                ),
            ],
            options={
                "db_table": "customer_phones",
                "ordering": ["-is_primary", "phone_type"],
            },
        ),
    ]
