# Generated by Django 5.0.9 on 2026-04-03 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loans", "0017_customeremail_customerphone"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="employment_start_date",
            field=models.DateField(
                blank=True, help_text="Fecha de inicio en el empleo actual", null=True
            ),
        ),
    ]
