# Generated by Django 5.0.9 on 2026-04-04 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loans", "0018_customer_employment_start_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="employment_start_date",
            field=models.DateField(
                blank=True, help_text="Fecha de ingreso al empleo actual", null=True
            ),
        ),
    ]
