# Generated by Django 5.0.9 on 2026-03-31 21:44

import django.db.models.deletion
import djmoney.models.fields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("loans", "0016_alter_collateral_appraisal_value_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CashRegister",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Nombre de la caja (ej: Caja Principal)",
                        max_length=100,
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Código único (ej: CAJA-01)",
                        max_length=20,
                        unique=True,
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True, help_text="Ubicación física", max_length=200
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "default_cashier",
                    models.ForeignKey(
                        blank=True,
                        help_text="Cajero asignado por defecto",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_registers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "cashbox_registers",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="CashSession",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("opened_at", models.DateTimeField(auto_now_add=True)),
                (
                    "opening_balance_currency",
                    djmoney.models.fields.CurrencyField(
                        choices=[
                            ("DOP", "Dominican Peso"),
                            ("EUR", "Euro"),
                            ("USD", "US Dollar"),
                        ],
                        default="DOP",
                        editable=False,
                        max_length=3,
                    ),
                ),
                (
                    "opening_balance",
                    djmoney.models.fields.MoneyField(
                        decimal_places=2,
                        help_text="Balance de apertura (efectivo contado al abrir)",
                        max_digits=14,
                    ),
                ),
                ("opening_notes", models.TextField(blank=True)),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "closing_balance_currency",
                    djmoney.models.fields.CurrencyField(
                        choices=[
                            ("DOP", "Dominican Peso"),
                            ("EUR", "Euro"),
                            ("USD", "US Dollar"),
                        ],
                        default="DOP",
                        editable=False,
                        max_length=3,
                        null=True,
                    ),
                ),
                (
                    "closing_balance",
                    djmoney.models.fields.MoneyField(
                        blank=True,
                        decimal_places=2,
                        help_text="Balance de cierre (efectivo contado al cerrar)",
                        max_digits=14,
                        null=True,
                    ),
                ),
                (
                    "expected_balance_currency",
                    djmoney.models.fields.CurrencyField(
                        choices=[
                            ("DOP", "Dominican Peso"),
                            ("EUR", "Euro"),
                            ("USD", "US Dollar"),
                        ],
                        default="DOP",
                        editable=False,
                        max_length=3,
                        null=True,
                    ),
                ),
                (
                    "expected_balance",
                    djmoney.models.fields.MoneyField(
                        blank=True,
                        decimal_places=2,
                        help_text="Balance esperado (calculado por sistema)",
                        max_digits=14,
                        null=True,
                    ),
                ),
                (
                    "difference_currency",
                    djmoney.models.fields.CurrencyField(
                        choices=[
                            ("DOP", "Dominican Peso"),
                            ("EUR", "Euro"),
                            ("USD", "US Dollar"),
                        ],
                        default="DOP",
                        editable=False,
                        max_length=3,
                        null=True,
                    ),
                ),
                (
                    "difference",
                    djmoney.models.fields.MoneyField(
                        blank=True,
                        decimal_places=2,
                        help_text="Diferencia (faltante o sobrante)",
                        max_digits=14,
                        null=True,
                    ),
                ),
                ("closing_notes", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Abierta"),
                            ("closing", "En cierre"),
                            ("closed", "Cerrada"),
                            ("reconciled", "Conciliada"),
                        ],
                        default="open",
                        max_length=20,
                    ),
                ),
                (
                    "cashier",
                    models.ForeignKey(
                        help_text="Cajero que abrió la caja",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cash_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "closed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="closed_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "register",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to="cashbox.cashregister",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "cashbox_sessions",
                "ordering": ["-opened_at"],
            },
        ),
        migrations.CreateModel(
            name="CashMovement",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "movement_type",
                    models.CharField(
                        choices=[("inflow", "Entrada"), ("outflow", "Salida")],
                        max_length=10,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("loan_payment", "Pago de préstamo"),
                            ("loan_payoff", "Saldo de préstamo"),
                            ("commission", "Comisión cobrada"),
                            ("late_fee", "Mora cobrada"),
                            ("insurance", "Seguro cobrado"),
                            ("other_income", "Otro ingreso"),
                            ("loan_disbursement", "Desembolso de préstamo"),
                            ("expense", "Gasto operativo"),
                            ("withdrawal", "Retiro de efectivo"),
                            ("refund", "Devolución"),
                            ("salary", "Pago de nómina"),
                            ("other_expense", "Otro gasto"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "amount_currency",
                    djmoney.models.fields.CurrencyField(
                        choices=[
                            ("DOP", "Dominican Peso"),
                            ("EUR", "Euro"),
                            ("USD", "US Dollar"),
                        ],
                        default="DOP",
                        editable=False,
                        max_length=3,
                    ),
                ),
                (
                    "amount",
                    djmoney.models.fields.MoneyField(decimal_places=2, max_digits=14),
                ),
                ("description", models.CharField(max_length=300)),
                (
                    "reference",
                    models.CharField(
                        blank=True,
                        help_text="Número de referencia, recibo, etc.",
                        max_length=100,
                    ),
                ),
                (
                    "customer_name",
                    models.CharField(
                        blank=True,
                        help_text="Nombre del cliente (desnormalizado)",
                        max_length=200,
                    ),
                ),
                (
                    "loan",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cash_movements",
                        to="loans.loan",
                    ),
                ),
                (
                    "loan_payment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cash_movements",
                        to="loans.loanpayment",
                    ),
                ),
                (
                    "recorded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cash_movements",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="movements",
                        to="cashbox.cashsession",
                    ),
                ),
            ],
            options={
                "db_table": "cashbox_movements",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DenominationCount",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "count_type",
                    models.CharField(
                        choices=[("opening", "Apertura"), ("closing", "Cierre")],
                        max_length=10,
                    ),
                ),
                (
                    "bills_2000",
                    models.IntegerField(default=0, help_text="Billetes de RD$2,000"),
                ),
                (
                    "bills_1000",
                    models.IntegerField(default=0, help_text="Billetes de RD$1,000"),
                ),
                (
                    "bills_500",
                    models.IntegerField(default=0, help_text="Billetes de RD$500"),
                ),
                (
                    "bills_200",
                    models.IntegerField(default=0, help_text="Billetes de RD$200"),
                ),
                (
                    "bills_100",
                    models.IntegerField(default=0, help_text="Billetes de RD$100"),
                ),
                (
                    "bills_50",
                    models.IntegerField(default=0, help_text="Billetes de RD$50"),
                ),
                (
                    "coins_25",
                    models.IntegerField(default=0, help_text="Monedas de RD$25"),
                ),
                (
                    "coins_10",
                    models.IntegerField(default=0, help_text="Monedas de RD$10"),
                ),
                (
                    "coins_5",
                    models.IntegerField(default=0, help_text="Monedas de RD$5"),
                ),
                (
                    "coins_1",
                    models.IntegerField(default=0, help_text="Monedas de RD$1"),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="denomination_counts",
                        to="cashbox.cashsession",
                    ),
                ),
            ],
            options={
                "db_table": "cashbox_denomination_counts",
            },
        ),
    ]
