# Generated by Django 5.0.9 on 2025-10-30 16:51

import djmoney.models.fields
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="enable_automated_reports",
            field=models.BooleanField(
                default=False, help_text="Enviar reportes automáticos por email"
            ),
        ),
        migrations.AddField(
            model_name="tenant",
            name="enable_email_reminders",
            field=models.BooleanField(
                default=True, help_text="Enviar recordatorios por email"
            ),
        ),
        migrations.AddField(
            model_name="tenant",
            name="enable_paypal",
            field=models.BooleanField(
                default=False,
                help_text="Habilitar pagos con PayPal (principalmente USA)",
            ),
        ),
        migrations.AddField(
            model_name="tenant",
            name="enable_sms_reminders",
            field=models.BooleanField(
                default=False,
                help_text="Enviar recordatorios por SMS (requiere configuración de API)",
            ),
        ),
        migrations.AddField(
            model_name="tenant",
            name="enable_stripe",
            field=models.BooleanField(
                default=False,
                help_text="Habilitar pagos con Stripe (principalmente USA)",
            ),
        ),
        migrations.AddField(
            model_name="tenant",
            name="enable_whatsapp_reminders",
            field=models.BooleanField(
                default=True,
                help_text="Enviar recordatorios por WhatsApp (requiere configuración de API)",
            ),
        ),
        migrations.AddField(
            model_name="tenant",
            name="grace_period_days",
            field=models.IntegerField(
                default=0, help_text="Días de gracia antes de aplicar mora (ej: 3 días)"
            ),
        ),
        migrations.AddField(
            model_name="tenant",
            name="late_fee_fixed_amount",
            field=djmoney.models.fields.MoneyField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Monto fijo de mora",
                max_digits=10,
            ),
        ),
        migrations.AddField(
            model_name="tenant",
            name="late_fee_fixed_amount_currency",
            field=djmoney.models.fields.CurrencyField(
                choices=[
                    ("DOP", "Dominican Peso"),
                    ("EUR", "Euro"),
                    ("USD", "US Dollar"),
                ],
                default="USD",
                editable=False,
                max_length=3,
            ),
        ),
        migrations.AddField(
            model_name="tenant",
            name="late_fee_frequency",
            field=models.CharField(
                choices=[
                    ("daily", "Por Día"),
                    ("monthly", "Por Mes"),
                    ("one_time", "Único al Vencer"),
                ],
                default="monthly",
                help_text="Frecuencia de aplicación de mora",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="tenant",
            name="late_fee_percentage",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("5.00"),
                help_text="Porcentaje de mora (ej: 5.00 = 5% del saldo vencido)",
                max_digits=5,
            ),
        ),
        migrations.AddField(
            model_name="tenant",
            name="late_fee_type",
            field=models.CharField(
                choices=[
                    ("percentage", "Porcentaje del Saldo"),
                    ("fixed", "Monto Fijo"),
                    ("none", "Sin Mora"),
                ],
                default="percentage",
                help_text="Tipo de cargo por mora",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="tenant",
            name="notification_email_from",
            field=models.EmailField(
                blank=True,
                help_text="Email desde donde se envían notificaciones (opcional)",
                max_length=254,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="tenant",
            name="paypal_client_id",
            field=models.CharField(
                blank=True, help_text="PayPal Client ID", max_length=255, null=True
            ),
        ),
        migrations.AddField(
            model_name="tenant",
            name="paypal_client_secret",
            field=models.CharField(
                blank=True,
                help_text="PayPal Client Secret (encriptada)",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="tenant",
            name="paypal_mode",
            field=models.CharField(
                choices=[
                    ("sandbox", "Sandbox (Pruebas)"),
                    ("live", "Live (Producción)"),
                ],
                default="sandbox",
                help_text="Modo de operación de PayPal",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="tenant",
            name="reminder_days_before",
            field=models.IntegerField(
                default=3,
                help_text="Días antes del vencimiento para enviar recordatorio",
            ),
        ),
        migrations.AddField(
            model_name="tenant",
            name="report_frequency",
            field=models.CharField(
                choices=[
                    ("daily", "Diario"),
                    ("weekly", "Semanal"),
                    ("monthly", "Mensual"),
                ],
                default="weekly",
                help_text="Frecuencia de envío de reportes",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="tenant",
            name="report_recipients",
            field=models.TextField(
                blank=True,
                help_text="Emails para recibir reportes (separados por coma)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="tenant",
            name="stripe_public_key",
            field=models.CharField(
                blank=True,
                help_text="Stripe Publishable Key",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="tenant",
            name="stripe_secret_key",
            field=models.CharField(
                blank=True,
                help_text="Stripe Secret Key (encriptada)",
                max_length=255,
                null=True,
            ),
        ),
    ]
