# Generated by Django 5.0.9 on 2025-10-30 18:21

import djmoney.models.fields
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0002_add_collection_config"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="accepted_payment_methods",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text='Lista de métodos de pago aceptados (ej: ["cash", "bank_transfer", "card"])',
            ),
        ),
        migrations.AddField(
            model_name="tenant",
            name="allow_early_repayment",
            field=models.BooleanField(
                default=True, help_text="Permitir pago anticipado del préstamo"
            ),
        ),
        migrations.AddField(
            model_name="tenant",
            name="allow_multiple_currencies",
            field=models.BooleanField(
                default=False, help_text="Permitir préstamos en múltiples monedas"
            ),
        ),
        migrations.AddField(
            model_name="tenant",
            name="allow_partial_disbursement",
            field=models.BooleanField(
                default=False, help_text="Permitir desembolsos parciales del préstamo"
            ),
        ),
        migrations.AddField(
            model_name="tenant",
            name="auto_approval_max_amount",
            field=djmoney.models.fields.MoneyField(
                blank=True,
                decimal_places=2,
                default=Decimal("1000.00"),
                help_text="Monto máximo para auto-aprobación automática",
                max_digits=14,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="tenant",
            name="auto_approval_max_amount_currency",
            field=djmoney.models.fields.CurrencyField(
                choices=[
                    ("DOP", "Dominican Peso"),
                    ("EUR", "Euro"),
                    ("USD", "US Dollar"),
                ],
                default="USD",
                editable=False,
                max_length=3,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="tenant",
            name="collateral_required_above",
            field=djmoney.models.fields.MoneyField(
                blank=True,
                decimal_places=2,
                default=Decimal("10000.00"),
                help_text="Requerir colateral para préstamos mayores a este monto",
                max_digits=14,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="tenant",
            name="collateral_required_above_currency",
            field=djmoney.models.fields.CurrencyField(
                choices=[
                    ("DOP", "Dominican Peso"),
                    ("EUR", "Euro"),
                    ("USD", "US Dollar"),
                ],
                default="USD",
                editable=False,
                max_length=3,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="tenant",
            name="credit_score_for_auto_approval",
            field=models.IntegerField(
                blank=True,
                default=700,
                help_text="Score crediticio mínimo para auto-aprobación",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="tenant",
            name="default_currency",
            field=models.CharField(
                choices=[
                    ("USD", "US Dollar ($)"),
                    ("DOP", "Dominican Peso (RD$)"),
                    ("EUR", "Euro (€)"),
                    ("GBP", "British Pound (£)"),
                ],
                default="USD",
                help_text="Moneda predeterminada para préstamos",
                max_length=3,
            ),
        ),
        migrations.AddField(
            model_name="tenant",
            name="default_grace_period_days",
            field=models.IntegerField(
                default=0,
                help_text="Días de gracia predeterminados antes del primer pago",
            ),
        ),
        migrations.AddField(
            model_name="tenant",
            name="default_interest_rate",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("12.00"),
                help_text="Tasa de interés anual predeterminada (ej: 12.00 = 12%)",
                max_digits=5,
            ),
        ),
        migrations.AddField(
            model_name="tenant",
            name="default_loan_term_months",
            field=models.IntegerField(
                default=12, help_text="Plazo predeterminado del préstamo en meses"
            ),
        ),
        migrations.AddField(
            model_name="tenant",
            name="default_loan_type",
            field=models.CharField(
                choices=[
                    ("personal", "Personal"),
                    ("business", "Empresarial"),
                    ("mortgage", "Hipotecario"),
                    ("auto", "Vehicular"),
                    ("education", "Educativo"),
                ],
                default="personal",
                help_text="Tipo de préstamo predeterminado",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="tenant",
            name="default_payment_frequency",
            field=models.CharField(
                choices=[
                    ("daily", "Diario"),
                    ("weekly", "Semanal"),
                    ("biweekly", "Quincenal"),
                    ("monthly", "Mensual"),
                ],
                default="monthly",
                help_text="Frecuencia de pago predeterminada",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="tenant",
            name="early_repayment_penalty",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Penalidad por pago anticipado (porcentaje del saldo restante)",
                max_digits=5,
            ),
        ),
        migrations.AddField(
            model_name="tenant",
            name="enable_auto_approval",
            field=models.BooleanField(
                default=False,
                help_text="Permitir auto-aprobación de préstamos bajo cierto monto",
            ),
        ),
        migrations.AddField(
            model_name="tenant",
            name="enable_bank_transfer_payments",
            field=models.BooleanField(
                default=True, help_text="Aceptar transferencias bancarias"
            ),
        ),
        migrations.AddField(
            model_name="tenant",
            name="enable_card_payments",
            field=models.BooleanField(
                default=False, help_text="Aceptar pagos con tarjeta de crédito/débito"
            ),
        ),
        migrations.AddField(
            model_name="tenant",
            name="enable_cash_payments",
            field=models.BooleanField(
                default=True, help_text="Aceptar pagos en efectivo"
            ),
        ),
        migrations.AddField(
            model_name="tenant",
            name="enable_check_payments",
            field=models.BooleanField(
                default=True, help_text="Aceptar pagos con cheque"
            ),
        ),
        migrations.AddField(
            model_name="tenant",
            name="enable_mobile_payments",
            field=models.BooleanField(
                default=False, help_text="Aceptar pagos móviles (ej: Yappy, ACH móvil)"
            ),
        ),
        migrations.AddField(
            model_name="tenant",
            name="enabled_loan_types",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text='Lista de tipos de préstamo habilitados (ej: ["personal", "business", "auto"])',
            ),
        ),
        migrations.AddField(
            model_name="tenant",
            name="enhanced_verification_amount",
            field=djmoney.models.fields.MoneyField(
                blank=True,
                decimal_places=2,
                default=Decimal("5000.00"),
                help_text="Monto a partir del cual se requiere verificación adicional de documentos",
                max_digits=14,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="tenant",
            name="enhanced_verification_amount_currency",
            field=djmoney.models.fields.CurrencyField(
                choices=[
                    ("DOP", "Dominican Peso"),
                    ("EUR", "Euro"),
                    ("USD", "US Dollar"),
                ],
                default="USD",
                editable=False,
                max_length=3,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="tenant",
            name="enhanced_verification_documents",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text='Documentos adicionales requeridos para montos altos (ej: ["bank_statement", "tax_return"])',
            ),
        ),
        migrations.AddField(
            model_name="tenant",
            name="guarantor_required_above",
            field=djmoney.models.fields.MoneyField(
                blank=True,
                decimal_places=2,
                default=Decimal("10000.00"),
                help_text="Requerir garante para préstamos mayores a este monto",
                max_digits=14,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="tenant",
            name="guarantor_required_above_currency",
            field=djmoney.models.fields.CurrencyField(
                choices=[
                    ("DOP", "Dominican Peso"),
                    ("EUR", "Euro"),
                    ("USD", "US Dollar"),
                ],
                default="USD",
                editable=False,
                max_length=3,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="tenant",
            name="max_active_loans_per_customer",
            field=models.IntegerField(
                default=3, help_text="Número máximo de préstamos activos por cliente"
            ),
        ),
        migrations.AddField(
            model_name="tenant",
            name="max_interest_rate",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("36.00"),
                help_text="Tasa de interés anual máxima permitida",
                max_digits=5,
            ),
        ),
        migrations.AddField(
            model_name="tenant",
            name="max_loan_amount",
            field=djmoney.models.fields.MoneyField(
                decimal_places=2,
                default=Decimal("50000.00"),
                help_text="Monto máximo de préstamo",
                max_digits=14,
            ),
        ),
        migrations.AddField(
            model_name="tenant",
            name="max_loan_amount_currency",
            field=djmoney.models.fields.CurrencyField(
                choices=[
                    ("DOP", "Dominican Peso"),
                    ("EUR", "Euro"),
                    ("USD", "US Dollar"),
                ],
                default="USD",
                editable=False,
                max_length=3,
            ),
        ),
        migrations.AddField(
            model_name="tenant",
            name="max_loan_term_months",
            field=models.IntegerField(
                default=60, help_text="Plazo máximo del préstamo en meses (5 años)"
            ),
        ),
        migrations.AddField(
            model_name="tenant",
            name="min_interest_rate",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("5.00"),
                help_text="Tasa de interés anual mínima permitida",
                max_digits=5,
            ),
        ),
        migrations.AddField(
            model_name="tenant",
            name="min_loan_amount",
            field=djmoney.models.fields.MoneyField(
                decimal_places=2,
                default=Decimal("100.00"),
                help_text="Monto mínimo de préstamo",
                max_digits=14,
            ),
        ),
        migrations.AddField(
            model_name="tenant",
            name="min_loan_amount_currency",
            field=djmoney.models.fields.CurrencyField(
                choices=[
                    ("DOP", "Dominican Peso"),
                    ("EUR", "Euro"),
                    ("USD", "US Dollar"),
                ],
                default="USD",
                editable=False,
                max_length=3,
            ),
        ),
        migrations.AddField(
            model_name="tenant",
            name="min_loan_term_months",
            field=models.IntegerField(
                default=1, help_text="Plazo mínimo del préstamo en meses"
            ),
        ),
        migrations.AddField(
            model_name="tenant",
            name="minimum_credit_score",
            field=models.IntegerField(
                default=300, help_text="Score crediticio mínimo requerido (300-850)"
            ),
        ),
        migrations.AddField(
            model_name="tenant",
            name="require_bank_statement",
            field=models.BooleanField(
                default=False, help_text="Requerir estado de cuenta bancario"
            ),
        ),
        migrations.AddField(
            model_name="tenant",
            name="require_collateral_default",
            field=models.BooleanField(
                default=False, help_text="Requerir colateral/garantía por defecto"
            ),
        ),
        migrations.AddField(
            model_name="tenant",
            name="require_credit_score",
            field=models.BooleanField(
                default=False, help_text="Requerir score crediticio para aprobación"
            ),
        ),
        migrations.AddField(
            model_name="tenant",
            name="require_disbursement_approval",
            field=models.BooleanField(
                default=True,
                help_text="Requiere aprobación adicional para desembolsar fondos",
            ),
        ),
        migrations.AddField(
            model_name="tenant",
            name="require_employment_letter",
            field=models.BooleanField(
                default=False, help_text="Requerir carta de empleo"
            ),
        ),
        migrations.AddField(
            model_name="tenant",
            name="require_guarantor",
            field=models.BooleanField(
                default=False, help_text="Requerir garante/fiador para préstamos"
            ),
        ),
        migrations.AddField(
            model_name="tenant",
            name="require_id_document",
            field=models.BooleanField(
                default=True, help_text="Requerir documento de identificación"
            ),
        ),
        migrations.AddField(
            model_name="tenant",
            name="require_proof_of_address",
            field=models.BooleanField(
                default=False, help_text="Requerir comprobante de domicilio"
            ),
        ),
        migrations.AddField(
            model_name="tenant",
            name="require_proof_of_income",
            field=models.BooleanField(
                default=True, help_text="Requerir comprobante de ingresos"
            ),
        ),
        migrations.AddField(
            model_name="tenant",
            name="supported_currencies",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text='Lista de monedas soportadas (ej: ["USD", "DOP", "EUR"])',
            ),
        ),
    ]
