# Generated by Django 5.0.9 on 2025-11-01 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0003_tenant_accepted_payment_methods_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="currency_symbol",
            field=models.CharField(
                default="$",
                help_text="Símbolo de la moneda (ej: $, RD$, €, £)",
                max_length=10,
            ),
        ),
    ]
