# Generated by Django 5.0.9 on 2025-11-04 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0004_add_currency_symbol"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="whatsapp_business_account_id",
            field=models.CharField(
                blank=True,
                help_text="WhatsApp Business Account ID",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="tenant",
            name="whatsapp_phone_id",
            field=models.CharField(
                blank=True,
                help_text="WhatsApp Phone Number ID from Meta Business",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="tenant",
            name="whatsapp_token",
            field=models.CharField(
                blank=True,
                help_text="WhatsApp Access Token from Meta Business (encriptado)",
                max_length=500,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="tenant",
            name="whatsapp_verify_token",
            field=models.CharField(
                blank=True,
                help_text="Webhook Verify Token (para validar webhooks)",
                max_length=100,
                null=True,
            ),
        ),
    ]
