# Generated by Django 5.0.9 on 2025-11-04 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0005_tenant_whatsapp_business_account_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="imap_host",
            field=models.CharField(
                blank=True,
                help_text="Servidor IMAP para recepción de correos (ej: imap.gmail.com)",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="tenant",
            name="imap_password",
            field=models.CharField(
                blank=True,
                help_text="Contraseña IMAP (se almacena encriptada)",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="tenant",
            name="imap_port",
            field=models.IntegerField(
                blank=True,
                default=993,
                help_text="Puerto IMAP (993 para SSL, 143 para no SSL)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="tenant",
            name="imap_use_ssl",
            field=models.BooleanField(
                default=True, help_text="Usar SSL para conexión IMAP"
            ),
        ),
        migrations.AddField(
            model_name="tenant",
            name="imap_username",
            field=models.CharField(
                blank=True,
                help_text="Usuario para autenticación IMAP (puede ser el mismo que SMTP)",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="tenant",
            name="smtp_host",
            field=models.CharField(
                blank=True,
                help_text="Servidor SMTP para envío de correos (ej: smtp.gmail.com)",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="tenant",
            name="smtp_password",
            field=models.CharField(
                blank=True,
                help_text="Contraseña SMTP (se almacena encriptada)",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="tenant",
            name="smtp_port",
            field=models.IntegerField(
                blank=True,
                default=587,
                help_text="Puerto SMTP (587 para TLS, 465 para SSL)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="tenant",
            name="smtp_use_ssl",
            field=models.BooleanField(
                default=False,
                help_text="Usar SSL para conexión SMTP (alternativa a TLS)",
            ),
        ),
        migrations.AddField(
            model_name="tenant",
            name="smtp_use_tls",
            field=models.BooleanField(
                default=True, help_text="Usar TLS para conexión SMTP"
            ),
        ),
        migrations.AddField(
            model_name="tenant",
            name="smtp_username",
            field=models.CharField(
                blank=True,
                help_text="Usuario para autenticación SMTP",
                max_length=255,
                null=True,
            ),
        ),
    ]
