# Generated by Django 5.0.9 on 2026-01-05 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0006_tenant_imap_host_tenant_imap_password_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="whatsapp_app_secret",
            field=models.CharField(
                blank=True,
                help_text="App Secret de Meta para validar firmas de webhook (HMAC-SHA256)",
                max_length=100,
                null=True,
            ),
        ),
    ]
