# Generated by Django 5.0.9 on 2026-03-29 22:01

import djmoney.models.fields
from decimal import Decimal
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0007_add_whatsapp_app_secret"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tenant",
            name="auto_approval_max_amount",
            field=djmoney.models.fields.MoneyField(
                blank=True,
                decimal_places=2,
                default=Decimal("1000.00"),
                default_currency="USD",
                help_text="Monto máximo para auto-aprobación automática",
                max_digits=14,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="tenant",
            name="collateral_required_above",
            field=djmoney.models.fields.MoneyField(
                blank=True,
                decimal_places=2,
                default=Decimal("10000.00"),
                default_currency="USD",
                help_text="Requerir colateral para préstamos mayores a este monto",
                max_digits=14,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="tenant",
            name="enhanced_verification_amount",
            field=djmoney.models.fields.MoneyField(
                blank=True,
                decimal_places=2,
                default=Decimal("5000.00"),
                default_currency="USD",
                help_text="Monto a partir del cual se requiere verificación adicional de documentos",
                max_digits=14,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="tenant",
            name="guarantor_required_above",
            field=djmoney.models.fields.MoneyField(
                blank=True,
                decimal_places=2,
                default=Decimal("10000.00"),
                default_currency="USD",
                help_text="Requerir garante para préstamos mayores a este monto",
                max_digits=14,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="tenant",
            name="late_fee_fixed_amount",
            field=djmoney.models.fields.MoneyField(
                decimal_places=2,
                default=Decimal("0.00"),
                default_currency="USD",
                help_text="Monto fijo de mora",
                max_digits=10,
            ),
        ),
        migrations.AlterField(
            model_name="tenant",
            name="max_loan_amount",
            field=djmoney.models.fields.MoneyField(
                decimal_places=2,
                default=Decimal("50000.00"),
                default_currency="USD",
                help_text="Monto máximo de préstamo",
                max_digits=14,
            ),
        ),
        migrations.AlterField(
            model_name="tenant",
            name="min_loan_amount",
            field=djmoney.models.fields.MoneyField(
                decimal_places=2,
                default=Decimal("100.00"),
                default_currency="USD",
                help_text="Monto mínimo de préstamo",
                max_digits=14,
            ),
        ),
    ]
