# Generated by Django 5.0.9 on 2025-11-04 01:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("loans", "0012_contract_archived_at_contract_archived_by_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Email",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "direction",
                    models.CharField(
                        choices=[("inbound", "Recibido"), ("outbound", "Enviado")],
                        default="outbound",
                        help_text="Dirección del correo (enviado o recibido)",
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Borrador"),
                            ("sent", "Enviado"),
                            ("delivered", "Entregado"),
                            ("read", "Leído"),
                            ("failed", "Fallido"),
                            ("received", "Recibido"),
                        ],
                        default="draft",
                        help_text="Estado del correo",
                        max_length=20,
                    ),
                ),
                (
                    "from_email",
                    models.EmailField(
                        help_text="Dirección de correo del remitente", max_length=255
                    ),
                ),
                (
                    "to_email",
                    models.EmailField(
                        help_text="Dirección de correo del destinatario", max_length=255
                    ),
                ),
                (
                    "cc",
                    models.TextField(
                        blank=True,
                        help_text="Direcciones en copia (CC), separadas por comas",
                        null=True,
                    ),
                ),
                (
                    "bcc",
                    models.TextField(
                        blank=True,
                        help_text="Direcciones en copia oculta (BCC), separadas por comas",
                        null=True,
                    ),
                ),
                (
                    "subject",
                    models.CharField(help_text="Asunto del correo", max_length=255),
                ),
                (
                    "body_text",
                    models.TextField(help_text="Contenido del correo en texto plano"),
                ),
                (
                    "body_html",
                    models.TextField(
                        blank=True, help_text="Contenido del correo en HTML", null=True
                    ),
                ),
                (
                    "message_id",
                    models.CharField(
                        blank=True,
                        help_text="ID único del mensaje de email",
                        max_length=255,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "in_reply_to",
                    models.CharField(
                        blank=True,
                        help_text="ID del mensaje al que responde",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "references",
                    models.TextField(
                        blank=True, help_text="Referencias a otros mensajes", null=True
                    ),
                ),
                (
                    "has_attachments",
                    models.BooleanField(
                        default=False,
                        help_text="Indica si el correo tiene archivos adjuntos",
                    ),
                ),
                (
                    "attachments_metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Metadata de archivos adjuntos (nombre, tamaño, tipo)",
                    ),
                ),
                (
                    "sent_at",
                    models.DateTimeField(
                        blank=True, help_text="Fecha y hora de envío", null=True
                    ),
                ),
                (
                    "received_at",
                    models.DateTimeField(
                        blank=True, help_text="Fecha y hora de recepción", null=True
                    ),
                ),
                (
                    "read_at",
                    models.DateTimeField(
                        blank=True, help_text="Fecha y hora de lectura", null=True
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Fecha de creación del registro"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="Fecha de última actualización"
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True,
                        help_text="Mensaje de error si el envío falló",
                        null=True,
                    ),
                ),
                (
                    "retry_count",
                    models.IntegerField(
                        default=0, help_text="Número de intentos de reenvío"
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        help_text="Cliente relacionado con el correo",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="emails",
                        to="loans.customer",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="Usuario que envió o recibió el correo",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="emails",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Email",
                "verbose_name_plural": "Emails",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["message_id"], name="communicati_message_8b6f46_idx"
                    ),
                    models.Index(
                        fields=["from_email"], name="communicati_from_em_6ad631_idx"
                    ),
                    models.Index(
                        fields=["to_email"], name="communicati_to_emai_e32642_idx"
                    ),
                    models.Index(
                        fields=["customer"], name="communicati_custome_b72419_idx"
                    ),
                    models.Index(
                        fields=["status"], name="communicati_status_81600a_idx"
                    ),
                    models.Index(
                        fields=["direction"], name="communicati_directi_180573_idx"
                    ),
                    models.Index(
                        fields=["-created_at"], name="communicati_created_f6e005_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="WhatsAppMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "direction",
                    models.CharField(
                        choices=[("inbound", "Recibido"), ("outbound", "Enviado")],
                        default="outbound",
                        help_text="Dirección del mensaje (enviado o recibido)",
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pendiente"),
                            ("sent", "Enviado"),
                            ("delivered", "Entregado"),
                            ("read", "Leído"),
                            ("failed", "Fallido"),
                            ("received", "Recibido"),
                        ],
                        default="pending",
                        help_text="Estado del mensaje",
                        max_length=20,
                    ),
                ),
                (
                    "message_type",
                    models.CharField(
                        choices=[
                            ("text", "Texto"),
                            ("image", "Imagen"),
                            ("audio", "Audio"),
                            ("video", "Video"),
                            ("document", "Documento"),
                            ("location", "Ubicación"),
                            ("template", "Plantilla"),
                        ],
                        default="text",
                        help_text="Tipo de mensaje",
                        max_length=20,
                    ),
                ),
                (
                    "wa_message_id",
                    models.CharField(
                        help_text="ID único del mensaje de WhatsApp",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "from_phone",
                    models.CharField(
                        help_text="Número de teléfono del remitente (formato E.164)",
                        max_length=50,
                    ),
                ),
                (
                    "to_phone",
                    models.CharField(
                        help_text="Número de teléfono del destinatario (formato E.164)",
                        max_length=50,
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        blank=True, help_text="Contenido del mensaje (texto)", null=True
                    ),
                ),
                (
                    "media_url",
                    models.URLField(
                        blank=True,
                        help_text="URL del archivo multimedia (imagen, video, audio, documento)",
                        max_length=500,
                        null=True,
                    ),
                ),
                (
                    "media_type",
                    models.CharField(
                        blank=True,
                        help_text="Tipo MIME del archivo multimedia",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "caption",
                    models.TextField(
                        blank=True,
                        help_text="Leyenda para archivos multimedia",
                        null=True,
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Metadata adicional del mensaje (ubicación, botones, etc.)",
                    ),
                ),
                (
                    "conversation_id",
                    models.CharField(
                        db_index=True,
                        help_text="ID de la conversación (normalmente el número del cliente)",
                        max_length=100,
                    ),
                ),
                (
                    "sent_at",
                    models.DateTimeField(
                        blank=True, help_text="Fecha y hora de envío", null=True
                    ),
                ),
                (
                    "delivered_at",
                    models.DateTimeField(
                        blank=True, help_text="Fecha y hora de entrega", null=True
                    ),
                ),
                (
                    "read_at",
                    models.DateTimeField(
                        blank=True, help_text="Fecha y hora de lectura", null=True
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Fecha de creación del registro"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="Fecha de última actualización"
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True,
                        help_text="Mensaje de error si el envío falló",
                        null=True,
                    ),
                ),
                (
                    "retry_count",
                    models.IntegerField(
                        default=0, help_text="Número de intentos de reenvío"
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        help_text="Cliente relacionado con el mensaje",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="whatsapp_messages",
                        to="loans.customer",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="Usuario que envió o recibió el mensaje",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="whatsapp_messages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Mensaje de WhatsApp",
                "verbose_name_plural": "Mensajes de WhatsApp",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["wa_message_id"], name="communicati_wa_mess_5d5d7e_idx"
                    ),
                    models.Index(
                        fields=["from_phone"], name="communicati_from_ph_b7c77c_idx"
                    ),
                    models.Index(
                        fields=["to_phone"], name="communicati_to_phon_7e208f_idx"
                    ),
                    models.Index(
                        fields=["conversation_id"],
                        name="communicati_convers_7a62ca_idx",
                    ),
                    models.Index(
                        fields=["customer"], name="communicati_custome_794a7d_idx"
                    ),
                    models.Index(
                        fields=["status"], name="communicati_status_820e84_idx"
                    ),
                    models.Index(
                        fields=["direction"], name="communicati_directi_42527d_idx"
                    ),
                    models.Index(
                        fields=["-created_at"], name="communicati_created_35db5a_idx"
                    ),
                ],
            },
        ),
    ]
