# Generated by Django 5.0.9 on 2025-12-13 21:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("communications", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="ID único de la tarea",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "title",
                    models.CharField(help_text="Título de la tarea", max_length=255),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Descripción detallada de la tarea",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("todo", "Por Hacer"),
                            ("in_progress", "En Progreso"),
                            ("review", "En Revisión"),
                            ("done", "Completado"),
                        ],
                        default="todo",
                        help_text="Estado actual de la tarea",
                        max_length=20,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Baja"),
                            ("medium", "Media"),
                            ("high", "Alta"),
                        ],
                        default="medium",
                        help_text="Prioridad de la tarea",
                        max_length=20,
                    ),
                ),
                (
                    "due_date",
                    models.DateField(
                        blank=True, help_text="Fecha límite de la tarea", null=True
                    ),
                ),
                (
                    "tags",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Etiquetas de la tarea (lista de strings)",
                    ),
                ),
                (
                    "position",
                    models.IntegerField(
                        default=0,
                        help_text="Posición de la tarea en la columna (para ordenamiento)",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="Fecha de última actualización"
                    ),
                ),
                (
                    "assignee",
                    models.ForeignKey(
                        blank=True,
                        help_text="Usuario asignado a la tarea",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_tasks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        help_text="Usuario que creó la tarea",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_tasks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Tarea",
                "verbose_name_plural": "Tareas",
                "ordering": ["position", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status"], name="communicati_status_612bcc_idx"
                    ),
                    models.Index(
                        fields=["priority"], name="communicati_priorit_ed11c5_idx"
                    ),
                    models.Index(
                        fields=["assignee"], name="communicati_assigne_e86123_idx"
                    ),
                    models.Index(
                        fields=["due_date"], name="communicati_due_dat_7cdb81_idx"
                    ),
                    models.Index(
                        fields=["position"], name="communicati_positio_f4ac1b_idx"
                    ),
                    models.Index(
                        fields=["-created_at"], name="communicati_created_5d3e2c_idx"
                    ),
                ],
            },
        ),
    ]
