# Generated by Django 5.0.9 on 2025-12-13 22:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("communications", "0002_add_task_model"),
        ("loans", "0012_contract_archived_at_contract_archived_by_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="customer",
            field=models.ForeignKey(
                blank=True,
                help_text="Cliente/Contacto relacionado con la tarea",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tasks",
                to="loans.customer",
            ),
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(
                fields=["customer"], name="communicati_custome_bf9f0f_idx"
            ),
        ),
    ]
